// This assembly is included in the following assemblies:
//
// <List assemblies here, each on a new line>

////
Retains the context of the parent assembly if this assembly is nested within another assembly.
For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
See also the complementary step on the last line of this file.
////

ifdef::context[:parent-context: {context}]

[id="assembly-upgrading-service-telemetry-framework-to-version-1-4_{context}"]
= Upgrading Service Telemetry Framework to version 1.4

// The `context` attribute enables module reuse. Every module's ID
// includes {context}, which ensures that the module has a unique ID even if
// it is reused multiple times in a guide.
:context: assembly-upgrading-service-telemetry-framework-to-version-1-4

[role="_abstract"]
To migrate from {Project} ({ProjectShort}) v1.3 to {ProjectShort} v1.4, you must replace the `ClusterServiceVersion` and `Subscription` objects in the `service-telemetry` namespace on your {OpenShift} environment.

.Prerequisites

* You have upgraded your {OpenShift} environment to v4.8. {ProjectShort} v1.4 does not run on {OpenShift} versions less than v4.8.
* You have backed up your data prior to any upgrade of the environment. Upgrading {ProjectShort} v1.3 to v1.4 results in a brief outage while the Smart Gateways and other components are updated. Additionally, changes to the `ServiceTelemetry` and `SmartGateway` objects do not have any effect while the Operators are being replaced.

To upgrade from {ProjectShort} v1.3 to v1.4, complete the following procedures:

.Procedure

. xref:removing-smart-gateway-1-3-operator_assembly-upgrading-service-telemetry-framework-to-version-1-4[Remove the {ProjectShort} 1.3 Smart Gateway Operator].
. xref:updating-the-service-telemetry-operator-to-1-4_assembly-upgrading-service-telemetry-framework-to-version-1-4[Update the Service Telemetry Operator to 1.4].


include::../modules/proc_removing-smart-gateway-1-3-operator.adoc[leveloffset=+1]
include::../modules/proc_updating-the-service-telemetry-operator-to-1-4.adoc[leveloffset=+1]

// The following line is necessary to allow assemblies be included in other
// assemblies. It restores the `context` variable to its previous state.
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
