// This assembly is included in the following assemblies:
//
// <List assemblies here, each on a new line>

////
Retains the context of the parent assembly if this assembly is nested within another assembly.
For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
See also the complementary step on the last line of this file.
////

ifdef::context[:parent-context: {context}]

[id='assembly-preparing-your-ocp-environment-for-stf_{context}']
= Preparing your {OpenShift} environment for {Project}

// The `context` attribute enables module reuse. Every module's ID
// includes {context}, which ensures that the module has a unique ID even if
// it is reused multiple times in a guide.
:context: assembly-preparing-your-ocp-environment-for-stf

[role="_abstract"]
As you prepare your {OpenShiftShort} environment for {ProjectShort}, you must plan for persistent storage, adequate resources, and event storage:

* Ensure that persistent storage is available in your {OpenShift} cluster to permit a production grade deployment. For more information, see <<persistent-volumes_assembly-preparing-your-ocp-environment-for-stf>>.
* Ensure that enough resources are available to run the Operators and the application containers. For more information, see <<resource-allocation_assembly-preparing-your-ocp-environment-for-stf>>.
* To install ElasticSearch, you must use a community catalog source. If you do not want to use a community catalog or if you do not want to store events, see <<deploying-stf-to-the-openshift-environment_assembly-installing-the-core-components-of-stf>>.
* {ProjectShort} uses ElasticSearch to store events, which requires a larger than normal `vm.max_map_count`. The `vm.max_map_count` value is set by default in {OpenShift}. For more information about how to edit the value of `vm.max_map_count`, see <<node-tuning-operator_assembly-preparing-your-ocp-environment-for-stf>>.

include::../modules/con_persistent-volumes.adoc[leveloffset=+1]
include::../modules/con_ephemeral-storage.adoc[leveloffset=+2]
include::../modules/con_resource-allocation.adoc[leveloffset=+1]
include::../modules/con_metrics-retention-time-period.adoc[leveloffset=+1]
include::../modules/con_node-tuning-operator.adoc[leveloffset=+1]


//reset the context
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
