// This assembly is included in the following assemblies:
//
// <List assemblies here, each on a new line>

////
Retains the context of the parent assembly if this assembly is nested within another assembly.
For more information about nesting assemblies, see: https://redhat-documentation.github.io/modular-docs/#nesting-assemblies
See also the complementary step on the last line of this file.
////

ifdef::context[:parent-context: {context}]

[id="assembly-introduction-to-stf_{context}"]
= Introduction to {Project} {TargetVersion}

// The `context` attribute enables module reuse. Every module's ID
// includes {context}, which ensures that the module has a unique ID even if
// it is reused multiple times in a guide.
:context: assembly-introduction-to-stf

// The following block is rendered only if the `internal` variable is set.
// The table shows various metadata useful when editing this file.

ifeval::["{build}" == "downstream"]
[IMPORTANT]
{Project} ({ProjectShort}) is compatible with {OpenShift}  versions {SupportedOpenShiftVersion} and {NextSupportedOpenShiftVersion}.

//For more information about migrating, see https://access.redhat.com/articles/5477371[Migrating Service Telemetry Framework v1.0 from OperatorSource to CatalogSource].
endif::[]

[role="_abstract"]
{Project} ({ProjectShort}) receives monitoring data from {OpenStack} or third-party nodes. You can use {ProjectShort} {ProjectShort} to monitor functions such as alert generation, visualization through dashboards, and single source of truth telemetry analysis to support orchestration.The monitoring data can be either of two types:

Metric:: a numeric measurement of an application or system
Event:: irregular and discrete occurrences that happen in a system

The data collection components on the client side are lightweight. The multicast message bus, which is shared by all clients and the deployment, provides fast and reliable data transport. Other modular components that receive and store data are deployed in containers on {OpenShiftShort}.

ifeval::["{build}" == "downstream"]
include::../modules/con_support-for-stf.adoc[leveloffset=+1]
endif::[]

include::../modules/con_stf-architecture.adoc[leveloffset=+1]

include::../modules/con_installation-size-of-ocp.adoc[leveloffset=+1]

ifeval::["{build}" == "upstream"]
include::../modules/con_development-environment-resource-requirements.adoc[leveloffset=+2]
endif::[]


//reset the context
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
