ifdef::context[:parent-context: {context}]

[id="assembly-introduction-to-stf_{context}"]
= Introduction to {Project} {TargetVersion}

// The `context` attribute enables module reuse. Every module's ID
// includes {context}, which ensures that the module has a unique ID even if
// it is reused multiple times in a guide.
:context: assembly-introduction-to-stf

// The following block is rendered only if the `internal` variable is set.
// The table shows various metadata useful when editing this file.

[role="_abstract"]
{Project} ({ProjectShort}) collects monitoring data from {OpenStack} ({OpenStackShort}) or third-party nodes. You can use {ProjectShort} to perform the following tasks:

* Store or archive the monitoring data for historical information.
* View the monitoring data graphically on the dashboard.
* Use the monitoring data to trigger alerts or warnings.

The monitoring data can be either metric or event:

Metric:: A numeric measurement of an application or system.
Event:: Irregular and discrete occurrences that happen in a system.

The message bus provides fast, reliable data transport and is shared by all the clients in the deployment. Other modular components that receive and store data, for example, Prometheus and ElasticSearch,  are deployed in containers on {OpenShift}.

ifeval::["{build}" == "downstream"]
[IMPORTANT]
{Project} ({ProjectShort}) is compatible with {OpenShift} versions {SupportedOpenShiftVersion} through {NextSupportedOpenShiftVersion}.
endif::[]

ifeval::["{build}" == "downstream"]
include::../modules/con_support-for-stf.adoc[leveloffset=+1]
endif::[]

include::../modules/con_stf-architecture.adoc[leveloffset=+1]

include::../modules/con_installation-size-of-ocp.adoc[leveloffset=+1]

ifeval::["{build}" == "upstream"]
include::../modules/con_development-environment-resource-requirements.adoc[leveloffset=+2]
endif::[]


//reset the context
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
