language: generic

git:
  depth: false

install:
- docker pull fedora:30

script:
- docker run -eGH_NAME -eGH_EMAIL -eGH_TOKEN --network host -it --volume $PWD:/docs:z --workdir /docs fedora:30 /bin/bash -c './build_tools/travis.sh'
