// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_installing-the-core-components-of-saf.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id='installing-the-core-components-of-saf_{context}']
= The core components of {ProjectShort}

When you install {ProjectShort}, use the `oc` tool or web interface to load Kubernetes
manifests into {OpenShiftShort}. The manifests set the required state of objects, for
example, creating a deployment. You can find the manifests for {ProjectShort}
in the `deploy/` directory of the telemetry-framework release archive.

For a copy of the deployment manifests and installation script, go to
link:https://github.com/redhat-service-assurance/telemetry-framework/releases[https://github.com/redhat-service-assurance/telemetry-framework/releases].

Loading the manifests results in the instantiation of the
link:https://coreos.com/blog/introducing-operators.html[Operators] into memory.
You can also load additional manifests into memory where the Operators manage
the deployment of application components, manage their life cycles, application
configurations, and so on.

{ProjectShort} has these core components:

* Prometheus and the AlertManager
* ElasticSearch
* Smart Gateway
* {MessageBus}

Each component has a corresponding Operator you can use to load the various
application components and objects.

To prepare your environment for {ProjectShort}, complete the following
procedures:

. Prepare your {OpenShiftShort} environment for {ProjectShort}. For more information, see <<preparing-your-openshift-environment-for-saf_installing-the-core-components-of-saf>>.

ifeval::["{build}" == "downstream"]
. Create an RHCC Secret. For more information, see <<creating-an-rhcc-secret_installing-the-core-components-of-saf>>.
endif::[]

. Generate a TLS certificate for {MessageBus}. For more information, see
<<generating-a-tls-certificate-for-amq-interconnect_installing-the-core-components-of-saf>>.

. Generate TLS certificates for ElasticSearch. For more information, see
<<generating-tls-certificates-for-elasticsearch_installing-the-core-components-of-saf>>.

. Deploy {ProjectShort} to the {OpenShiftShort} environment. For more information, see <<deploying-saf-to-the-openshift-environment_installing-the-core-components-of-saf>>.
