// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_creating-and-importing-an-rhcc-secret.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id='creating-an-rhcc-secret_{context}']
= Creating an RHCC Secret

To import the applicable container images from the Red Hat Container Catalog (RHCC), you must create an RHCC secret. For more information about getting started with the RHCC, see link:https://access.redhat.com/containers/#/started[Red Hat Container Catalog Get Started Guide].

To create an RHCC secret, complete the following steps:

. Create a registry service account. For more information, see link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].

. Create a manifest that you can load into OpenShift. This instantiates a secret resource to use for importing the container images from RHCC. Download the `<unique_name>-auth.json` file from the _Docker Configuration_ tab after creating your authentication. Create the following sample manifest for your registry service account in the `sa-telemetry` namespace previously created:

+
----
cat > serviceassurance-auth.json <<EOF
{
"auths": {
"registry.redhat.io": {
"auth": "NjM0MD..."
                      }
         }
}

EOF
----
+
. Use the `oc` tool to create the secret resource:
+
----
oc create secret generic serviceassurance-pull-secret --from-file=".dockerconfigjson=serviceassurance-auth.json" --type='kubernetes.io/dockerconfigjson'
----
