// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_container-versions.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id='container-versions_{context}']
= Container Versions

When deploying SAF you can choose to use container images from either upstream
(public open source), or downstream (published to the Red Hat Container Catalog).
Two scripts,`import-downstream.sh` and `import-upstream.sh` are provided to help
with this. In the scripts we attempt to hook into specific versions for
deployment from the source registry. When importing those into our ImageStream
source for delivery of the images from the internal OpenShift registry, we often
use `latest` where possible. In certain instances an Operator or container
artifact may require a specific version format, and thus is reflected in the
container image tag imported into the internal registry.

In the future we hope to better align the versions across the various
ImageStreams and to build a more consistent view between the deployment
methods. It's possible our issues will be resolved with the migration to the
Operator Lifecycle Manager as well.
