// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_configuring-red-hat-openstack-platform-overcloud-for-stf.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id='configuring-red-hat-openstack-platform-overcloud-for-stf-events_{context}']
= Configuring the {OpenStack} overcloud for {ProjectShort} events

To enable the collection of events on the client side, follow the steps in
<<configuring-red-hat-openstack-platform-overcloud-for-stf_completing-the-stf-configuration>> and use the following sample from `metrics-collectd-qdr-overrides.yaml` for this procedure.
You can pass the `metrics-collectd-qdr-overrides.yaml` environment file to a {OpenstackLong} {OpenStackInstaller} deployment to configure and setup collectd and {MessageBus}.

.metrics-collectd-qdr-overrides.yaml
[source,yaml]
----
---
parameter_defaults:
  CollectdAmqpInstances:
  notify: # Create a `notify` address for {MessageBus} that transmits the events.
    format: JSON # The format of the messages is in JSON.
    presettle: false
    notify: true # Mark these messages as being events in the VES format.
  telemetry:
    format: JSON
    presettle: true
  CollectdDefaultPollingInterval: 1
  CollectdConnectionType: amqp1
  CollectdExtraPlugins:
  - cpu
  - df
  - hugepages
  - ovs_stats
  - ovs_events # Enable an events plugin for OVS events.
  - connectivity # Enable an events plugin for network connectivity events.
  - load
  - uptime
  MetricsQdrConnectors:
  - host: qdr-white-port-5671-sa-telemetry.apps.service-assurance.tld
    port: 443
    role: edge
    sslProfile: sslProfile
    verifyHostname: false
  MetricsQdrSSLProfiles:
  - name: sslProfile
----
