// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_deploying-smart-gateways.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="deploying-smart-gateways_{context}"]
= Deploying Smart Gateways

You must deploy two Smart Gateways for each cloud; one for metrics and one for events. Configure both Smart Gateways to listen on the AMQP address defined for the corresponding cloud.

When you deploy SAF for the first time, two Smart Gateway manifests are created that define the two initial Smart Gateways for a single cloud. When you deploy  multiple Smart Gateways, you must edit these manifests to define the Smart Gateways handling the metrics and the events data for each cloud.

To deploy multiple Smart Gateways, complete the following steps:

. Edit the following Smart Gateway manifests to define a Smart Gateway for each cloud: `deploy/service-assurance/smartgateway/metrics-smartgateway.yaml` and `deploy/service-assurance/smartgateway/events-smartgateway.yaml`. For more information, see
<<example-manifests_connecting-multiple-clouds-to-saf>>.
. Delete the existing Smart Gateways from the cluster.
+
----
oc delete smartgateway --all
----
. Deploy your new Smart Gateways.
+
----
oc create -f deploy/service-assurance/smartgateway/
----
. Verify that each Smart Gateway is running. This can take several minutes
depending on the number of Smart Gateways.
+
----
oc get po -l app=smart-gateway
----
