// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/con_sizing-your-installation.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: con_my-concept-module-a.adoc
// * ID: [id='con_my-concept-module-a_{context}']
// * Title: = My concept module A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// In the title, include nouns that are used in the body text. This helps
// readers and search engines find information quickly.
// Do not start the title with a verb. See also _Wording of headings_
// in _The IBM Style Guide_.
[id="installation-size_{context}"]
= Installation size

The size of your {OpenShift} installation depends on the following factors:

* The number of nodes you want to monitor.
* The number of metrics you want to collect.
* The resolution of metrics.
* The length of time that you want to store the data.

Installation of {Project} ({ProjectShort}) depends on an existing {OpenShift} environment. Ensure that you install monitoring for {OpenStack} on a platform separate from your {OpenStack} environment. You can install {OpenShift} ({OpenShiftShort}) on baremetal or other supported cloud platforms. For more information about installing {OpenShiftShort}, see https://docs.openshift.com/container-platform/4.3/welcome/index.html#cluster-installer-activities[OpenShift Container Platform 4.3 Documentation].

The size of your {OpenShiftShort} environment depends on the infrastructure you select. For more information about minimum resources requirements when installing {OpenShiftShort} on baremetal, see https://docs.openshift.com/container-platform/4.3/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal[Minimum resource requirements] in the _Installing a cluster on bare metal_ guide. For installation requirements of the various public and private cloud platforms which you can install, see the corresponding installation documentation for your cloud of choice.

ifeval::["{build}" == "upstream"]
[id="development-environment-resource-requirement_{context}"]
== Development environment resource requirements

You can create an all-in-one development environment for {ProjectShort} locally by using https://code-ready.github.io/crc/[CodeReady Containers]. The installation process of CodeReady Containers (CRC) is available at https://code-ready.github.io/crc/#installation_gsg.

The https://code-ready.github.io/crc/#minimum-system-requirements-hardware_gsg[minimum resource requirements] for CRC is not enough by default to run {ProjectShort}. Ensure that your host system has the following resources available:

* 4 physical cores (8 hyperthreaded cores)
* 64 GB of memory
* 80 GB of storage space

After you complete the installation of CRC, use the `crc start` command to start your environment. The recommended minimum system resources for running {ProjectShort} in CodeReady Containers is 48 GB of memory and 8 virtual CPU cores:

[source,bash]
----
crc start --memory=49152 --cpus=8
----

If you have an existing environment, delete it, and recreate it to ensure that the resource requests have an effect.

.Procedure

. Run the `crc delete` command.
+
[source,bash]
----
crc delete
----

. Run the `crc start` command to create your environment:
+
[source,bash]
----
crc start --memory=49152 --cpus=8
----
endif::[]
