[id="tls-certificates-duration_{context}"]
= Configuring the duration for the TLS certificates

[role="_abstract"]
You can configure the duration for the TLS certificates used for the connections with
Elasticsearch and {MessageBus} in {Project} ({ProjectShort}). To do so,
modify the `ServiceTelemetry` object and configure the `certificates` parameters.

[id="configuration-parameters-for-tls-certificates-duration_{context}"]
== Configuration parameters for the TLS certificates

The `certificates` parameter contains the following sub-parameters for configuring the
certificates duration:

endpointCertDuration:: The requested 'duration' (i.e. lifetime) of the endpoint Certificate.
Minimum accepted duration is 1 hour. Value must be in units accepted by Go time.ParseDuration https://golang.org/pkg/time/#ParseDuration.
Default value is `70080h`.
caCertDuration:: The requested 'duration' (i.e. lifetime) of the CA Certificate.
Minimum accepted duration is 1 hour. Value must be in units accepted by Go time.ParseDuration https://golang.org/pkg/time/#ParseDuration.
Default value is `70080h`.

NOTE:: Certificates are by default long lived considering a subset of them are expected to be copied in the {OpenStack}
deployment when they renew. For more information about the QDR CA Certificate renewal process, see
xref:assembly-renewing-the-amq-interconnect-certificate_assembly[]

The `certificates` parameter for Elasticsearch is part of the `backends.events.elasticsearch` definition and is configured in the `ServiceTelemetry` object:

[source,yaml,options="nowrap"]
----
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: default
  namespace: service-telemetry
spec:
...
  backends:
    ...
    events:
      elasticsearch:
        enabled: true
        version: 7.16.1
        certificates:
          endpointCertDuration: 70080h
          caCertDuration: 70080h
...
----

The `certificates` parameter for QDR is part of the `transports.qdr` definition and is configured in the `ServiceTelemetry` object:

[source,yaml,options="nowrap"]
----
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: default
  namespace: service-telemetry
spec:
...
  transports:
    ...
    qdr:
      enabled: true
      certificates:
        endpointCertDuration: 70080h
        caCertDuration: 70080h
...
----
