[id="installation-size-of-ocp_{context}"]
= Installation size of {OpenShift}

[role="_abstract"]
The size of your {OpenShift} installation depends on the following factors:

* The infrastructure you select.
* The number of nodes you want to monitor.
* The number of metrics you want to collect.
* The resolution of metrics.
* The length of time that you want to store the data.

Installation of {Project} ({ProjectShort}) depends on the existing {OpenShift} environment. Ensure that you install monitoring for {OpenStack} ({OpenStackShort}) on a platform separate from your {OpenStackShort} environment. You can install {OpenShift} on baremetal or other supported cloud platforms. For more information about installing {OpenShift}, see https://docs.openshift.com/container-platform/{SupportedOpenShiftVersion}/welcome/index.html#cluster-installer-activities[OpenShift Container Platform {SupportedOpenShiftVersion} Documentation].

For more information about minimum resources requirements when you install {OpenShift} on baremetal, see https://docs.openshift.com/container-platform/{SupportedOpenShiftVersion}/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal[Minimum resource requirements] in the _Installing a cluster on bare metal_ guide. For installation requirements of the various public and private cloud platforms that you can install, see the corresponding installation documentation for your cloud platform of choice.
