[id="dashboards_{context}"]
= Dashboards in {Project}

[role="_abstract"]
Use the third-party application, Grafana, to visualize system-level metrics that collectd and Ceilometer gathers for each individual host node.

For more information about configuring collectd, see xref:configuring-red-hat-openstack-platform-overcloud-for-stf_assembly-completing-the-stf-configuration[].

ifdef::include_when_16[]
//TODO: can re-work this once we have OSP13 dashboard(s) to show. Can't use container health checks or monitoring in OSP13.
You can use two dashboards to monitor a cloud:

Infrastructure dashboard::
Use the infrastructure dashboard to view metrics for a single node at a time. Select a node from the upper left corner of the dashboard.

Cloud view dashboard::
Use the cloud view dashboard to view panels to monitor service resource usage, API stats, and cloud events. You must enable API health monitoring and service monitoring to provide the data for this dashboard. API health monitoring is enabled by default in the {ProjectShort} base configuration. For more information, see xref:creating-the-base-configuration-for-stf_assembly-completing-the-stf-configuration
** For more information about API health monitoring, see xref:monitoring-container-health-and-api-status_assembly-advanced-features[].
** For more information about service monitoring, see xref:resource-usage-of-openstack-services_assembly-advanced-features[].
endif::include_when_16[]
