// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/con_alerts.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: con_my-concept-module-a.adoc
// * ID: [id='con_my-concept-module-a_{context}']
// * Title: = My concept module A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// In the title, include nouns that are used in the body text. This helps
// readers and search engines find information quickly.
// Do not start the title with a verb. See also _Wording of headings_
// in _The IBM Style Guide_.
[id="alerts_{context}"]
= Alerts

Alerting with Prometheus is separated into two parts. First, alerting rules in Prometheus servers send alerts to an Alertmanager. Second, the Alertmanager manages the alerts, including silencing, inhibition, aggregation, and sending out notifications using email, on-call notification systems, or chat platforms. You can configure alerts to receive notifications, for example, when the load average of a node gets higher than 1.0 or when a disk is almost full.

To create an alert, complete the following tasks:

. Create an alert rule in Prometheus. For more information, see <<creating-an-alert-rule-in-prometheus_advanced-features>>.
. Create an alert route in Alertmanager. For more information, see <<creating-an-alert-route-in-alertmanager_advanced-features>>.


[discrete]
== Additional resources

For more information about alerts or notifications with Prometheus and Alertmanager, see https://prometheus.io/docs/alerting/overview/

To view the set of alerts that you can use with {ProjectShort}, see https://github.com/infrawatch/service-telemetry-operator/blob/mrunge-add-alerts/deploy/alerts/alerts.yaml
