// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/con_sizing-your-installation.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: con_my-concept-module-a.adoc
// * ID: [id='con_my-concept-module-a_{context}']
// * Title: = My concept module A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// In the title, include nouns that are used in the body text. This helps
// readers and search engines find information quickly.
// Do not start the title with a verb. See also _Wording of headings_
// in _The IBM Style Guide_.
[id='installation-size_{context}']
= Installation size

The size of your {OpenShift} installation depends on the following factors:

* The number of nodes being monitored.
* The number of metrics being collected.
* The resolution of metrics.
* The length of time that you want to store the data.

Installation of {Project} ({ProjectShort}) is dependent on an existing {OpenShift} environment and it is recommended that monitoring of {OpenStack} be done on an installed platform separate of your {OpenStack} environment. Installation of {OpenShift} ({OpenShiftShort}) can be done on baremetal or various supported cloud platforms. Installation of {OpenShiftShort} is covered at https://docs.openshift.com/container-platform/4.3/welcome/index.html#cluster-installer-activities.

The sizing of {OpenShiftShort} is dependent on the infrastructure selected. More information about minimum resources requirements when installing {OpenShiftShort} on baremetal is available at https://docs.openshift.com/container-platform/4.3/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal. For installation requirements of the various public and private cloud platforms available to install to, see the corresponding installation documentation for your cloud of choice.

ifeval::["{build}" == "upstream"]
[id='development-environment-resource-requirement_{context}']
== Development environment resource requirements

An all-in-one development environment for {ProjectShort} can be locally created using https://code-ready.github.io/crc/[CodeReady Containers]. Installation process of CodeReady Containers (CRC) is available at https://code-ready.github.io/crc/#installation_gsg.

The https://code-ready.github.io/crc/#minimum-system-requirements-hardware_gsg[minimum resource requirements] for CRC is not enough by default to run {ProjectShort}. It is recommended that your host system has the following resources available:

* 4 physical cores (8 hyperthreaded cores)
* 64 GB of memory
* 80 GB of storage space

After completing the installation of CRC it is recommended you start your environment with the following commands:

----
crc start --memory=49152 --cpus=8
----

If you have an existing environment it must be destroyed and recreated in order for the resource requests to have an effect. To recreate the environment first run `crc delete` to delete the virtual machine, and then run the provided command to create your environment.
endif::[]
