// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/con_development-environment-resource-requirements.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: con_my-concept-module-a.adoc
// * ID: [id='con_my-concept-module-a_{context}']
// * Title: = My concept module A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// In the title, include nouns that are used in the body text. This helps
// readers and search engines find information quickly.
// Do not start the title with a verb. See also _Wording of headings_
// in _The IBM Style Guide_.

ifeval::["{build}" == "upstream"]
[id="development-environment-resource-requirements_{context}"]
= Development environment resource requirements


[role="_abstract"]
You can create an all-in-one development environment for {ProjectShort} locally by using https://code-ready.github.io/crc/[CodeReady Containers]. The installation process of CodeReady Containers (CRC) is available at https://code-ready.github.io/crc/#installation_gsg.

The https://code-ready.github.io/crc/#minimum-system-requirements-hardware_gsg[minimum resource requirements] for CRC is not enough by default to run {ProjectShort}. Ensure that your host system has the following resources available:

* 4 physical cores (8 hyperthreaded cores)
* 64 GB of memory
* 80 GB of storage space

After you complete the installation of CRC, use the `crc start` command to start your environment. The recommended minimum system resources for running {ProjectShort} in CodeReady Containers is 48 GB of memory and 8 virtual CPU cores:

[source,bash]
----
crc start --memory=49152 --cpus=8
----

If you have an existing environment, delete it, and recreate it to ensure that the resource requests have an effect.

.Procedure

. Enter the `crc delete` command.
+
[source,bash]
----
crc delete
----

. Run the `crc start` command to create your environment:
+
[source,bash]
----
crc start --memory=49152 --cpus=8
----
endif::[]
