// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_deploying-smart-gateways.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="deploying-smart-gateways_{context}"]
= Deploying Smart Gateways

You must deploy a Smart Gateway for each of the data collection types for each cloud; one for collectd metrics, one for collectd events, and one for Ceilometer events. Configure each of the Smart Gateways to listen on the AMQP address that you define for the corresponding cloud.

When you deploy {ProjectShort} for the first time, Smart Gateway manifests are created that define the initial Smart Gateways for a single cloud. When deploying Smart Gateways for multiple cloud support, you deploy multiple Smart Gateways for each of the data collection types that handle the metrics and the events data for each cloud. The initial Smart Gateways act as a template to create additional Smart Gateways, along with any authentication information required to connect to the data stores.

To deploy additional Smart Gateways for each cloud you want to monitor, complete the following steps:

. Switch to the `service-telemetry` project:
+
----
oc project service-telemetry
----

. Use the initially deployed Smart Gateways as a template for additional Smart Gateways. List the currently deployed Smart Gateways with `oc get SmartGateways`. Assuming you deployed with `metricsEnabled: true` and `eventsEnabled: true`, the following Smart Gateways are displayed in the output:
+
----
$ oc get smartgateways

NAME                                         AGE
stf-default-ceilometer-notification          14d
stf-default-collectd-notification            14d
stf-default-collectd-telemetry               14d
----

. Retrieve the manifests for each Smart Gateway and store the contents in a temporary file, which you can modify later and use to create the new set of Smart Gateways:
+
----
truncate --size 0 /tmp/cloud1-smartgateways.yaml && \
for sg in $(oc get smartgateways -oname)
do
  echo "---" >> /tmp/cloud1-smartgateways.yaml
  oc get ${sg} -oyaml --export >> /tmp/cloud1-smartgateways.yaml
done
----

. To modify the manifests, change the `metadata.name` field and `spec.amqpUrl` field to include the cloud identifier from your schema. For more information, see <<planning-amqp-address-prefixes_advanced-features>>. To view example Smart Gateway manifests, see <<example-manifests_advanced-features>>.

. Deploy your new Smart Gateways.
+
----
oc apply -f /tmp/cloud1-smartgateways.yaml
----

. Verify that each Smart Gateway is running. This can take several minutes depending on the number of Smart Gateways.
+
----
oc get po -l app=smart-gateway
----
