[id="deleting-the-default-smart-gateways_{context}"]
= Deleting the default Smart Gateways

[role="_abstract"]
After you configure {Project} ({ProjectShort}) for multiple clouds, you can delete the default Smart Gateways if they are no longer in use. The Service Telemetry Operator can remove `SmartGateway` objects that were created but are no longer listed in the ServiceTelemetry `clouds` list of objects. To enable the removal of SmartGateway objects that are not defined by the `clouds` parameter, you must set the `cloudsRemoveOnMissing` parameter to `true` in the `ServiceTelemetry` manifest.

TIP: If you do not want to deploy any Smart Gateways, define an empty clouds list by using the `clouds: []` parameter.

WARNING: The `cloudsRemoveOnMissing` parameter is disabled by default. If you enable the `cloudsRemoveOnMissing` parameter, you remove any manually created `SmartGateway` objects in the current namespace without any possibility to restore.

.Procedure

. Define your `clouds` parameter with the list of cloud objects that you want the Service Telemetry Operator to manage. For more information, see xref:clouds_assembly-installing-the-core-components-of-stf[].

. Edit the ServiceTelemetry object and add the `cloudsRemoveOnMissing` parameter:
+
[source,yaml]
----
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  ...
spec:
  ...
  cloudsRemoveOnMissing: true
  clouds:
    ...
----

. Save the modifications.

. Verify that the Operator deleted the Smart Gateways. This can take several minutes while the Operators reconcile the changes:
+
[source,bash]
----
$ oc get smartgateways
----
