= Sending metrics to Gnocchi and to {ProjectShort}

[role="_abstract"]

To send metrics to {Project} ({ProjectShort}} and gnocchi simultaneously, you must include another configuration file to your deployment. 
mentioned above.

.Prerequisites

* You have created a file that contains the connection configuration of the AMQ Interconnect for the overcloud to the {ProjectShort} deployment. For more information, see xref:configuring-the-stf-connection-for-the-overcloud[].

.Procedure

. Create a configuration file named `publish-to-gnocchi.yaml` in the
`/home/stack` directory.
+
[source,yaml]
----
resource_registry:
    OS::TripleO::Services::GnocchiApi: /usr/share/openstack-tripleo-heat-templates/deployment/gnocchi/gnocchi-api-container-puppet.yaml
    OS::TripleO::Services::GnocchiMetricd: /usr/share/openstack-tripleo-heat-templates/deployment/gnocchi/gnocchi-metricd-container-puppet.yaml
    OS::TripleO::Services::GnocchiStatsd: /usr/share/openstack-tripleo-heat-templates/deployment/gnocchi/gnocchi-statsd-container-puppet.yaml
    OS::TripleO::Services::AodhApi: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-api-container-puppet.yaml
    OS::TripleO::Services::AodhEvaluator: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-evaluator-container-puppet.yaml
    OS::TripleO::Services::AodhNotifier: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-notifier-container-puppet.yaml
    OS::TripleO::Services::AodhListener: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-listener-container-puppet.yaml
    OS::TripleO::Services::PankoApi: /usr/share/openstack-tripleo-heat-templates/deployment/deprecated/panko/panko-api-container-puppet.yaml

parameter_defaults:
    CeilometerEnableGnocchi: true
    CeilometerEnablePanko: false
    GnocchiArchivePolicy: 'high'
    GnocchiBackend: 'rbd'
    GnocchiRbdPoolName: 'metrics'

    EventPipelinePublishers: ['gnocchi://?filter_project=service&archive_policy=high']
    PipelinePublishers: ['gnocchi://?filter_project=service&archive_policy=high']
----

. Add the environment file `publish-to-gnocchi.yaml` to the deployment command:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ openstack overcloud deploy <other-arguments>
  --templates /usr/share/openstack-tripleo-heat-templates \
  --environment-file <...other-environment-files...> \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/ceilometer-write-qdr.yaml \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/enable-stf.yaml \
  --environment-file /home/stack/stf-connectors.yaml \
  --environment-file /home/stack/publish-to-gnocchi.yaml
----

. Verification: To verify that the configuration was successful, verify the content
of the file `/var/lib/config-data/puppet-generated/ceilometer/etc/ceilometer/pipeline.yaml` on a Controller
node:

[source,yaml]
----
sources:
    - name: meter_source
      meters:
          - "*"
      sinks:
          - meter_sink
sinks:
    - name: meter_sink
      publishers:
          - gnocchi://?filter_project=service&archive_policy=high
          - notifier://172.17.1.35:5666/?driver=amqp&topic=metering
----
+
Ensure that the `publishers` section of the file contains information for both notifier and gnocchi.
