

[id="deploying-stf-on-openshift-disconnected-environments_{context}"]
= Deploying {ProjectShort} on {OpenShift}-disconnected environments

[role="_abstract"]
Since {Project} ({ProjectShort}) version 1.5.4, you can deploy {ProjectShort} in {OpenShift}-disconnected environments.

.Prerequisites

* {OpenShift} Extended Update Support (EUS) version 4.12 or 4.14 deployed in a restricted network.
* A mirror registry so that the {OpenShift} cluster can access the required images. For more information about mirror registries, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpenShiftVersion}/html/installing/disconnected-installation-mirroring[Disconnected installation mirroring] in the {OpenShift} _Installing_ guide.
* All the {ProjectShort} dependencies are available in the {OpenShift} cluster mirror registry. 

.Adding {ProjectShort} dependencies to the mirror registry

You can use the `oc-mirror` plugin to fetch the {ProjectShort} dependencies and add them to the {OpenShift} cluster mirror registry. For more information about installing the `oc-mirror` plugin, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpenShiftVersion}/html-single/installing/index#installing-mirroring-disconnected[Mirroring images for a disconnected installation using the oc-mirror plugin] in the {OpenShift} _Installing_ guide.


.Procedure

. Create an imagesetconfig.yaml file in your local working directory:

+
[source,yaml,options="nowrap",role="white-space-pre"]
----
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: ./
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
      - name: service-telemetry-operator
        channels:
          - name: stable-1.5
      - name: openshift-cert-manager-operator
        channels:
          - name: stable-v1
      - name: amq7-interconnect-operator
        channels:
          - name: 1.10.x
      - name: smart-gateway-operator
        channels:
          - name: stable-1.5
      - name: cluster-observability-operator
        channels:
          - name: development
----


. (Optional) If your mirror registry is not reachable, you can save the manifests and images that you fetched with `oc-mirror` and physically transfer them to the mirror registry and {OpenShift} cluster. Otherwise you can run `oc-mirror` and point to the mirror registry.  

+
You can use the `oc-mirror` plugin differently, depending on your environment, such as:

* mirroring between mirrors.
* mirror from mirror to disk.
* mirror from disk to mirror.

+
For more information about different `oc-mirror` scenarios, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpenShiftVersion}/html/installing/disconnected-installation-mirroring#mirroring-image-set-full[Mirroring an image set in a fully disconnected environment] in the {OpenShift} _Installing_ guide.


. Push the {ProjectShort} operators and their dependencies from the mirror registry and generate the manifest for the {OpenShift} cluster.

+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc-mirror --config imagesetconfig.yaml <mirror_registry_location>
----

+
* Replace <mirror_registry_location> with the filepath to the mirror registry that you want to use.

+
. Locate the generated manifests and apply them to the target {OpenShift} cluster. For more information, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpenShiftVersion}/html/installing/disconnected-installation-mirroring#oc-mirror-updating-cluster-manifests_installing-mirroring-disconnected[Configuring your cluster to use the resources generated by oc-mirror] in the {OpenShift} _Installing_ guide.

+
NOTE: The manifests that you generate with `oc-mirror` produce catalogs with the full index name, such as `redhat-operator-index` instead of `redhat-operators` for `CatalogSource`. Ensure that you use the correct index name for the {ProjectShort}  subscriptions. For more information, see xref:deploying-stf-to-the-openshift-environment_assembly-installing-the-core-components-of-stf[]. For more information about customizing Operators with oc mirror, see the Red Hat Knowledgebase solution link:https://access.redhat.com/solutions/7016714[How to customize the catalog name and tags of Operators mirrored to the mirror registry using the oc mirror plugin.] 

.Verification

* Check that the catalog sources are applied. You can return the entries for new catalogs that reference the {ProjectShort} operators and their dependencies:

+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc get catalogsources
----

* You have deployed {ProjectShort} in a disconnected {OpenShift} cluster and therefore cannot access external networks.

