
[id="importing-dashboards_{context}"]
= Importing dashboards

[role="_abstract"]
The Grafana Operator can import and manage dashboards by creating `GrafanaDashboard` objects. You can view example dashboards at https://github.com/infrawatch/dashboards.

.Procedure

. Import the infrastructure dashboard:
+
[source,bash,options="nowrap"]
----
$ oc apply -f https://raw.githubusercontent.com/infrawatch/dashboards/master/deploy/stf-1/rhos-dashboard.yaml

grafanadashboard.integreatly.org/rhos-dashboard-1 created
----
. Import the cloud dashboard:
+
[WARNING]
For some panels in the cloud dashboard, you must set the value of the collectd `virt` plugin parameter `hostname_format` to `name uuid hostname` in the `stf-connectors.yaml` file. If you do not configure this parameter, affected dashboards remain empty. For more information about the `virt` plugin, see link:{defaultURL}/operational_measurements/collectd-plugins_assembly[collectd plugins].
+
[source,bash,options="nowrap"]
----
$ oc apply -f https://raw.githubusercontent.com/infrawatch/dashboards/master/deploy/stf-1/rhos-cloud-dashboard.yaml

grafanadashboard.integreatly.org/rhos-cloud-dashboard-1 created
----
. Import the cloud events dashboard:
+
[source,bash,options="nowrap"]
----
$ oc apply -f https://raw.githubusercontent.com/infrawatch/dashboards/master/deploy/stf-1/rhos-cloudevents-dashboard.yaml

grafanadashboard.integreatly.org/rhos-cloudevents-dashboard created
----
. Import the virtual machine dashboard:
+
[source,bash,options="nowrap"]
----
$ oc apply -f https://raw.githubusercontent.com/infrawatch/dashboards/master/deploy/stf-1/virtual-machine-view.yaml

grafanadashboard.integreatly.org/virtual-machine-view-1 configured
----
. Import the memcached dashboard:
+
[source,bash,options="nowrap"]
----
$ oc apply -f https://raw.githubusercontent.com/infrawatch/dashboards/master/deploy/stf-1/memcached-dashboard.yaml

grafanadashboard.integreatly.org/memcached-dashboard-1 created
----

. Verify that the dashboards are available:
+
[source,bash]
----
$ oc get grafanadashboards

NAME                   AGE
memcached-dashboard-1      115s
rhos-cloud-dashboard-1     2m12s
rhos-cloudevents-dashboard   2m6s
rhos-dashboard-1           2m17s
virtual-machine-view-1     2m
----

. Retrieve the Grafana route address:
+
[source,bash,options="nowrap"]
----
$ oc get route grafana-route -ojsonpath='{.spec.host}'

grafana-route-service-telemetry.apps.infra.watch
----

. In a web browser, navigate to https://_<grafana_route_address>_. Replace _<grafana_route_address>_ with the value that you retrieved in the previous step.

. To view the dashboard, click *Dashboards* and *Manage*.
