[id="setting-up-grafana-to-host-the-dashboard_{context}"]
= Configuring Grafana to host the dashboard

[role="_abstract"]
Grafana is not included in the default {Project} ({ProjectShort}) deployment, so you must deploy the Grafana Operator from community-operators CatalogSource. If you use the Service Telemetry Operator to deploy Grafana, it results in a Grafana instance and the configuration of the default data sources for the local {ProjectShort} deployment.

ifdef::include_16[The dashboards in {ProjectShort} require features that are available only in Grafana version 8.1.0 and later. By default, the Service Telemetry Operator installs a compatible version. For more information about how to override the Grafana container image, see xref:overriding-the-default-grafana-container-image_assembly-advanced-features[].]

.Procedure

. Log in to {OpenShift}.
. Change to the `service-telemetry` namespace:
+
[source,bash]
----
$ oc project service-telemetry
----

. Subscribe to the Grafana Operator by using the community-operators CatalogSource:
+
[WARNING]
====
Community Operators are Operators which have not been vetted or verified by Red Hat. Community Operators should be used with caution because their stability is unknown. Red Hat provides no support for community Operators.

https://access.redhat.com/third-party-software-support[Learn more about Red Hat’s third party software support policy]
====
+
[source,yaml]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: service-telemetry
spec:
  channel: v4
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
EOF
----

. Verify that the Operator launched successfully. In the command output, if the value of the `PHASE` column is `Succeeded`, the Operator launched successfully:
+
[source,bash,options="nowrap"]
----
$ oc wait --for jsonpath="{.status.phase}"=Running csv -l operators.coreos.com/grafana-operator.service-telemetry --timeout=600s

clusterserviceversion.operators.coreos.com/grafana-operator.v4.10.1 condition met
----

. To launch a Grafana instance, create or modify the `ServiceTelemetry` object. Set `graphing.enabled` and `graphing.grafana.ingressEnabled` to `true`. Optionally, set the  value of `graphing.grafana.baseImage` to the Grafana workload container image that will be deployed:
+
[source,bash]
----
$ oc edit stf default

apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
...
spec:
  ...
  graphing:
    enabled: true
    grafana:
      ingressEnabled: true
      baseImage: 'registry.redhat.io/rhel8/grafana:7'
----

. Verify that the Grafana instance deployed:
+
[source,bash]
----
$ oc wait --for jsonpath="{.status.phase}"=Running pod -l app=grafana --timeout=600s

pod/grafana-deployment-7566475c56-jlkjp condition met
----

. Verify that the Grafana data sources installed correctly:
+
[source,bash]
----
$ oc get grafanadatasources

NAME                    AGE
default-datasources     20h
----

. Verify that the Grafana route exists:
+
[source,bash,options="nowrap"]
----
$ oc get route grafana-route

NAME            HOST/PORT                                          PATH   SERVICES          PORT   TERMINATION   WILDCARD
grafana-route   grafana-route-service-telemetry.apps.infra.watch          grafana-service   3000   edge          None
----
