// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_creating-a-servicetelemetry-object-in-openshift.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.

[id="overview-of-the-servicetelemetry-object"]
== Overview of the ServiceTelemetry object.

IMPORTANT: Versions of Service Telemetry Operator prior to v1.1.0 used a flat API (`servicetelemetry.infra.watch/v1alpha1`) interface for creating the `ServiceTelemetry` object.
In Service Telemetry Operator v1.1.0 a dictionary-based API interface was created (`servicetelemetry.infra.watch/v1beta1`) to allow for better control of {ProjectShort} deployments, including managing multi-cluster deployments natively, and allowing the management of additional storage backends in the future.

To deploy the {Project}, you must create an instance of `ServiceTelemetry` in {OpenShiftShort}. The `ServiceTelemetry` object is made up of several major sections including:

* `alerting`
* `backends`
* `clouds`
* `graphing`
* `highAvailability`
* `transports`

Each of these top-level configuration parameters provides various controls for a {Project} deployment. For example, the `backends` parameter has several options to control the deployment of storage backends for metrics and events. The `clouds` parameter controls the deployment of `SmartGateway` objects that are consumed by the Smart Gateway Operator.

The following core parameters are available for a `ServiceTelemetry` manifest:

[[table-core-manifest-parameters]]
.Core parameters for a `ServiceTelemetry` manifest
|===
| Parameter | Description

| `backends` | Controls what storage backends are available for metrics and events. Also controls which Smart Gateway deployments are available and connected to storage backends.

| `clouds` | Controls which clouds can be connected to {ProjectShort} and what message bus address to subscribe for metrics and events for each of the data collector types supported by the Smart Gateyway (i.e. collectd and Ceilometer).

| `alerting` | Controls the management of alerts. For more information, see xref:alerting_advanced-features[].

| `graphing` | Controls options related to graphing data from the available storage backends. For more information, see xref:dashboards_advanced-features[].

| `highAvailability` | Controls options related to high availability in {ProjectShort}. For more information, see xref:high-availability_advanced-features[].

| `transports` | Controls options related to available data transports. The default is to enable the QDR backend, the only supported transport, and is required to be enabled for operation of {ProjectShort}. The default is `enabled: true`.

|===

Let's go through each of the top-level objects to understand how they support a deployment of {ProjectShort}.

=== Backends

The `backends` parameter controls both what storage backends are available for storage of metrics and events, and also controls the enablement of Smart Gateways as defined by the `clouds` parameter. See xref:Clouds[] for more information.

The available storage backends include `metrics` and `events`. The `metrics` backends include `Prometheus`, and the `events` backends include `ElasticSearch`.

To enable Prometheus as a storage backend for metrics, configure the `ServiceTelemetry` object:

[source,yaml]
----
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: stf-default
  namespace: service-telemetry
spec:
  backends:
    metrics:
      prometheus:
        enabled: true
----

As the parameters are a dictionary of parameters, referencing them in the documentation will to be presented using dotted notation. For example, the configuration example for enabling the Prometheus backend for storage of metrics would be noted as `backends.metrics.prometheus.enabled: true`.

To enable events support in {ProjectShort} requires prerequisite steps to ensure ElasticSearch can be started. For more information, see xref:subscribing-to-elastic-cloud-on-kubernetes-operator[]. By default, `backends.events.elasticsearch.enabled` is set to false. For more information, see xref:deploying-stf-to-the-openshift-environment-without-elasticsearch[].

=== Clouds

The `clouds` parameter controls what Smart Gateway objects are deployed, thereby providing the interface for multiple monitoring cloud enviornments to connect to an instance of {ProjectShort}. If a supporting backend is available, then metrics and events Smart Gateways for the default cloud configuration will be created. By default the Service Telemetry Operator will create Smart Gateways for `cloud1`.

A list of cloud objects can be created to allow control of which Smart Gateways are created for each cloud defined. Each cloud is made up of data types and collectors. Data types are one of `metrics` or `events`. Each data type is made up of a list of collectors and the message bus subscription address. Available collectors are `collectd` and `ceilometer`. The subscription address for each of these collectors should be unique for every cloud, data type, and collector combination.

The default `cloud1` configuration would be represented by the following `ServiceTelemetry` object, providing subscriptions and data storage of metrics and events for both collectd and Ceilometer data collectors for a particular cloud unit.

[source,yaml]
----
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: stf-default
  namespace: service-telemetry
spec:
  clouds:
    - name: cloud1
      metrics:
        collectors:
          - collectorType: collectd
            subscriptionAddress: collectd/telemetry
          - collectorType: ceilometer
            subscriptionAddress: anycast/ceilometer/metering.sample
      events:
        collectors:
          - collectorType: collectd
            subscriptionAddress: collectd/notify
          - collectorType: ceilometer
            subscriptionAddress: anycast/ceilometer/event.sample
----


=== Alerting

The `alerting` parameter controls creation of an [Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/) instance and the configuration of the storage backend. By default `alerting.enabled` is set to `true`. For more information, see xref:alerting_advanced-features[].

=== Graphing

The `graphing` parameter controls the creation of a [Grafana](https://grafana.com/docs/grafana/latest/getting-started/what-is-grafana/) instance. By default `graphing.enabled` is `false`. For more information, see xref:dashboards_advanced-features[].

=== High Availability

The `highAvailability` parameter controls the instantiation of multiple copies of {ProjectShort} components to reduce recovery time should components fail or be rescheduled. By default `highAvailability.enabled` is `false`. For more information, see xref:high-availability_advanced-features[].

=== Transports

The `transports` parameter controls the enablement of the message bus for a {ProjectShort} deployment. The only transport currently supported is {MessageBus}, and is required to be enabled for proper operation of {ProjectShort}. By default `transports.qdr.enabled` is `true`.

[id="creating-a-servicetelemetry-object-in-openshift"]
== Creating a ServiceTelemetry object in {OpenShiftShort}

Create a `ServiceTelemetry` object in {OpenShiftShort} to result in the creation of supporting components for a {Project} deployment. For more information, see xref:overview-of-the-servicetelemetry-object[].

.Procedure

. To store events in ElasticSearch, set `eventsEnabled` to true during deployment:
+
[source,bash]
----
oc apply -f - <<EOF
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: stf-default
  namespace: service-telemetry
spec:
  eventsEnabled: true
  metricsEnabled: true
EOF
----

. To view the {ProjectShort} deployment logs in the Service Telemetry Operator, use the `oc logs` command:
+
[source,bash]
----
oc logs $(oc get pod --selector='name=service-telemetry-operator' -oname) -c ansible
----
+
[options="nowrap", subs="+quotes"]
----
PLAY RECAP *********************************************************************
localhost                  : ok=68   changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
----



. View the pods and the status of each pod to determine that all workloads are operating nominally:
+
NOTE: If you set `eventsEnabled: true`, the notification Smart Gateways will `Error` and `CrashLoopBackOff` for a period of time before ElasticSearch starts.
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc get pods

NAME                                                              READY   STATUS             RESTARTS   AGE
alertmanager-stf-default-0                                        2/2     Running            0          26m
elastic-operator-645dc8b8ff-jwnzt                                 1/1     Running            0          88m
elasticsearch-es-default-0                                        1/1     Running            0          26m
interconnect-operator-6fd49d9fb9-4bl92                            1/1     Running            0          46m
prometheus-operator-bf7d97fb9-kwnlx                               1/1     Running            0          46m
prometheus-stf-default-0                                          3/3     Running            0          26m
service-telemetry-operator-54f4c99d9b-k7ll6                       2/2     Running            0          46m
smart-gateway-operator-7ff58bcf94-66rvx                           2/2     Running            0          46m
stf-default-ceilometer-notification-smartgateway-7c45b755bzhhw2   1/1     Running            2          26m
stf-default-ceilometer-telemetry-smartgateway-6c99864b45-fwqfc    1/1     Running            0          26m
stf-default-collectd-notification-smartgateway-787974df89-6xpr4   1/1     Running            2          26m
stf-default-collectd-telemetry-smartgateway-68f5cd5ffc-9758h      2/2     Running            0          26m
stf-default-interconnect-7458fd4d69-nqbfs                         1/1     Running            0          26m
----
