[id="proc-retrieving-and-setting-grafana-credentials_{context}"]
= Retrieving and setting Grafana login credentials

[role="_abstract"]
When Grafana is enabled, you can login using OpenShift authentication, or the default username and password set by the Grafana Operator.

[WARNING]
====
Ensure that you log in to access the dashboards with the _Log in with OpenShift_ button, because the default username and password set by the Grafana Operator is deprecated.
====

You can override the credentials in the `ServiceTelemetry` object to have {Project} ({ProjectShort}) set the username and password for Grafana instead.

.Procedure

. Log in to {OpenShift}.
. Change to the `service-telemetry` namespace:
+
[source,bash]
----
$ oc project service-telemetry
----
. Retrieve the existing username and password from the {ProjectShort} object:
+
[source,bash]
----
$ oc get stf default -o jsonpath="{.spec.graphing.grafana['adminUser','adminPassword']}"
----

. To modify the default values of the Grafana administrator username and password through the ServiceTelemetry object, use the `graphing.grafana.adminUser` and `graphing.grafana.adminPassword` parameters.
+
[source,bash]
----
$ oc edit stf default
----
. Wait for the grafana pod to restart with the new credentials in place
+
[source,bash]
----
$ oc get po -l app=grafana -w
----
