[id="deploying-the-overcloud_{context}"]
= Deploying the overcloud

[role="_abstract"]
Deploy or update the overcloud with the required environment files so that data is collected and transmitted to {Project} ({ProjectShort}).

.Procedure

. Log in to the {OpenStack} ({OpenStackShort}) undercloud as the `stack` user.

. Source the authentication file:
+
[source,bash]
----
[stack@undercloud-0 ~]$ source stackrc

(undercloud) [stack@undercloud-0 ~]$
----

. Add the following files to your {OpenStackShort} {OpenStackInstaller} deployment to configure data collection and {MessageBus}:
+
* The `collectd-write-qdr.yaml` file to ensure that collectd telemetry and events are sent to {ProjectShort}
* The `ceilometer-write-qdr.yaml` file to ensure that Ceilometer telemetry and events are sent to {ProjectShort}
* The `qdr-edge-only.yaml` file to ensure that the message bus is enabled and connected to {ProjectShort} message bus routers
* The `enable-stf.yaml` environment file to ensure defaults are configured correctly
* The `stf-connectors.yaml` environment file to define the connection to {ProjectShort}
+
// this one is actually a valid use of subs +quotes. We want the underbars to result in emphasis when generated.
+
[source,bash,options="nowrap",subs="+quotes"]
----
(undercloud) [stack@undercloud-0 ~]$ openstack overcloud deploy _<other_arguments>_
--templates /usr/share/openstack-tripleo-heat-templates \
  --environment-file _<...other_environment_files...>_ \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/ceilometer-write-qdr.yaml \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/collectd-write-qdr.yaml \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/qdr-edge-only.yaml \
  --environment-file /home/stack/enable-stf.yaml \
  --environment-file /home/stack/stf-connectors.yaml
----

. Deploy the {OpenStackShort} overcloud.
