[id="creating-an-alert-rule-in-prometheus_{context}"]
= Creating an alert rule in Prometheus

[role="_abstract"]
Prometheus evaluates alert rules to trigger notifications. If the rule condition returns an empty result set, the condition is false. Otherwise, the rule is true and it triggers an alert.

.Procedure

. Log in to {OpenShift}.
. Change to the `service-telemetry` namespace:
+
[source,bash]
----
$ oc project service-telemetry
----

. Create a `PrometheusRule` object that contains the alert rule. The Prometheus Operator loads the rule into Prometheus:
+
[source,bash,options="nowrap"]
----
$ oc apply -f - <<EOF
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: default
    role: alert-rules
  name: prometheus-alarm-rules
  namespace: service-telemetry
spec:
  groups:
    - name: ./openstack.rules
      rules:
        - alert: Metric Listener down
          expr: collectd_qpid_router_status < 1 # <1>
EOF
----
<1> To change the rule, edit the value of the expr parameter.

. To verify that the Operator loaded the rules  into Prometheus, create a pod with access to `curl`:
+
[source,bash]
----
$ oc run curl --generator=run-pod/v1 --image=radial/busyboxplus:curl -i --tty
----

. Run the `curl` command to access the `prometheus-operated` service to return the rules loaded into memory:
+
[source,bash,options="nowrap"]
----
[ root@curl:/ ]$ curl prometheus-operated:9090/api/v1/rules
{"status":"success","data":{"groups":[{"name":"./openstack.rules","file":"/etc/prometheus/rules/prometheus-default-rulefiles-0/service-telemetry-prometheus-alarm-rules.yaml","rules":[{"name":"Metric Listener down","query":"collectd_qpid_router_status \u003c 1","duration":0,"labels":{},"annotations":{},"alerts":[],"health":"ok","type":"alerting"}],"interval":30}]}}
----

. To verify that the output shows the rules loaded into the `PrometheusRule` object, for example the output contains the defined `./openstack.rules`, exit the pod:
+
[source,bash]
----
[ root@curl:/ ]$ exit
----

. Clean up the environment by deleting the `curl` pod:
+
[source,bash]
----
$ oc delete pod curl

pod "curl" deleted
----

.Additional resources

* For more information on alerting, see https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md
