////
* file name: proc_removing-the-service-telemetry-operator.adoc
* ID: [id="proc_removing-the-service-telemetry-operator_{context}"]
* Title: = Removing the Service Telemetry Operator
////
:_content-type: PROCEDURE

[id="removing-the-service-telemetry-operator_{context}"]
= Removing the Service Telemetry Operator

As part of upgrading your {Project} ({ProjectShort}) installation, you must remove the Service Telemetry Operator in the `service-telemetry` namespace on your {OpenShift} environment.

.Procedure

. Change to the `service-telemetry` project:
+
[source,bash]
----
$ oc project service-telemetry
----

. Remove the Service Telemetry Operator Subscription:
+
[source,bash]
----
$ oc delete sub --selector=operators.coreos.com/service-telemetry-operator.service-telemetry

subscription.operators.coreos.com "service-telemetry-operator" deleted
----

. Remove the Service Telemetry Operator `ClusterServiceVersion`:
+
[source,bash]
----
$ oc delete csv --selector=operators.coreos.com/service-telemetry-operator.service-telemetry

clusterserviceversion.operators.coreos.com "service-telemetry-operator.v1.4.1669718959" deleted
----

.Verification

. Verify that the Service Telemetry Operator deployment is not running:
+
[source,bash]
----
$ oc get deploy --selector=operators.coreos.com/service-telemetry-operator.service-telemetry

No resources found in service-telemetry namespace.
----

. Verify the Service Telemetry Operator subscription is absent:
+
[source,bash]
----
$ oc get sub --selector=operators.coreos.com/service-telemetry-operator.service-telemetry

No resources found in service-telemetry namespace.
----

. Verify the Service Telemetry Operator ClusterServiceVersion is absent:
+
[source,bash]
----
$ oc get csv --selector=operators.coreos.com/service-telemetry-operator.service-telemetry

No resources found in service-telemetry namespace.
----
