// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_deploying-smart-gateways.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="deploying-smart-gateways_{context}"]
= Deploying Smart Gateways

You must deploy a Smart Gateway for each of the data collection type for each cloud; one for collectd metrics, one for collectd events, and one for Ceilometer events. Configure each of the Smart Gateways to listen on the AMQP address that you define for the corresponding cloud.

When you deploy {ProjectShort} for the first time, Smart Gateway manifests are created that define the initial Smart Gateways for a single cloud. When deploying Smart Gateways for multiple cloud support, you deploy multiple Smart Gateways for each of the data collection types that handle the metrics and the events data for each cloud. The initial Smart Gateways will act as a template we can use to create additional Smart Gateways along with any authentication information required to connect to the data stores.

To deploy additional Smart Gateways for each cloud being monitored, complete the following steps:

. Use the initially deployed Smart Gateways as a template for additional Smart Gateways:
+
----

----

. Copy the following Smart Gateway manifests and edit them to define a Smart Gateway for each cloud: `deploy/service-telemetry/smartgateway/metrics-smartgateway.yaml` and `deploy/service-telemetry/smartgateway/events-smartgateway.yaml`. For more information, see <<example-manifests_advanced-features>>.
+
----
pushd deploy/service-telemetry/smartgateway/
cp events-smartgateway.yaml events-smartgateway-multicloud.yaml
cp metrics-smartgateway.yaml metrics-smartgateway-multicloud.yaml
vi events-smartgateway-multicloud.yaml metrics-smartgateway-multicloud.yaml
popd
----

. Deploy your new Smart Gateways.
+
----
oc create -f deploy/service-telemetry/smartgateway/
----
. Verify that each Smart Gateway is running. This can take several minutes
depending on the number of Smart Gateways.
+
----
oc get po -l app=smart-gateway
----
