[id="setting-up-grafana-to-host-the-dashboard_{context}"]
= Configuring Grafana to host the dashboard

[role="_abstract"]
Grafana is not included in the default {Project} ({ProjectShort}) deployment, so you must deploy the Grafana Operator from community-operators CatalogSource. If you use the Service Telemetry Operator to deploy Grafana, it results in a Grafana instance and the configuration of the default data sources for the local {ProjectShort} deployment.

.Procedure

. Log in to your {OpenShift} environment where {ProjectShort} is hosted.

. Subscribe to the Grafana Operator by using the community-operators CatalogSource:
+
[WARNING]
====
Community Operators are Operators which have not been vetted or verified by Red Hat. Community Operators should be used with caution because their stability is unknown. Red Hat provides no support for community Operators.

https://access.redhat.com/third-party-software-support[Learn more about Red Hat’s third party software support policy]
====
+
[source,yaml]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/grafana-operator.openshift-operators: ""
  name: grafana-operator
  namespace: openshift-operators
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
EOF
----

. Verify that the Operator launched successfully. In the command output, if the value of the `PHASE` column is `Succeeded`, the Operator launched successfully:
+
[source,bash,options="nowrap"]
----
$ oc wait --for jsonpath="{.status.phase}"=Succeeded csv --namespace openshift-operators -l operators.coreos.com/grafana-operator.openshift-operators

clusterserviceversion.operators.coreos.com/grafana-operator.v5.6.0 condition met
----

. To launch a Grafana instance, create or modify the `ServiceTelemetry` object. Set `graphing.enabled` and `graphing.grafana.ingressEnabled` to `true`. Optionally, set the  value of `graphing.grafana.baseImage` to the Grafana workload container image that will be deployed:
+
[source,bash]
----
$ oc edit stf default

apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
...
spec:
  ...
  graphing:
    enabled: true
    grafana:
      ingressEnabled: true
      baseImage: 'registry.redhat.io/rhel8/grafana:9'
----

. Verify that the Grafana instance deployed:
+
[source,bash,options="nowrap"]
----
$ oc wait --for jsonpath="{.status.phase}"=Running pod -l app=default-grafana --timeout=600s

pod/default-grafana-deployment-669968df64-wz5s2 condition met
----

. Verify that the Grafana data sources installed correctly:
+
[source,bash,options="nowrap"]
----
$ oc get grafanadatasources.grafana.integreatly.org

NAME                        NO MATCHING INSTANCES   LAST RESYNC   AGE
default-ds-stf-prometheus                           2m35s         2m56s
----

. Verify that the Grafana route exists:
+
[source,bash,options="nowrap"]
----
$ oc get route default-grafana-route

NAME                    HOST/PORT                                                   PATH   SERVICES                  PORT   TERMINATION   WILDCARD
default-grafana-route   default-grafana-route-service-telemetry.apps.infra.watch           default-grafana-service   web    reencrypt     None
----
