// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_subscribing-to-the-elastic-cloud-on-kubernetes-operator.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="subscribing-to-the-elastic-cloud-on-kubernetes-operator_{context}"]
= Subscribing to the Elastic Cloud on Kubernetes Operator

[role="_abstract"]
Before you install the Service Telemetry Operator and if you plan to store events in ElasticSearch, you must enable the Elastic Cloud Kubernetes Operator.

.Procedure

. To enable the Elastic Cloud on Kubernetes Operator, create the following manifest in your {OpenShiftShort} environment:
+
[source,bash]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elastic-cloud-eck
  namespace: service-telemetry
spec:
  channel: stable
  installPlanApproval: Automatic
  name: elastic-cloud-eck
  source: operatorhubio-operators
  sourceNamespace: openshift-marketplace
EOF
----

. Verify that the `ClusterServiceVersion` for ElasticSearch Cloud on Kubernetes `succeeded`:
+
[source,options="nowrap",subs="+quotes"]
----
$ oc get csv

NAME                       DISPLAY                        VERSION   REPLACES                   PHASE
...
elastic-cloud-eck.v1.6.0   Elasticsearch (ECK) Operator   1.6.0     elastic-cloud-eck.v1.5.0   Succeeded
----
