// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_setting-up-the-dashboard-to-host-grafana.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="setting-up-grafana-to-host-the-dashboard_{context}"]
= Setting up Grafana to host the dashboard

[role="_abstract"]
Grafana is not included in the default {Project} ({ProjectShort}) deployment so you must deploy the Grafana Operator from OperatorHub.io. Using the Service Telemetry Operator to deploy Grafana results in a Grafana instance and the  configuration of the default data sources for the local {ProjectShort} deployment.

.Prerequisites

Enable OperatorHub.io catalog source for the Grafana Operator. For more information, see xref:enabling-the-operatorhub-io-community-catalog-source_assembly-installing-the-core-components-of-stf[].

.Procedure

. Log in to {OpenShift}.
. Change to the `service-telemetry` namespace:
+
[source,bash]
----
$ oc project service-telemetry
----

. Deploy the Grafana operator:
+
[source,yaml]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: service-telemetry
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: grafana-operator
  source: operatorhubio-operators
  sourceNamespace: openshift-marketplace
EOF
----

. To verify that the operator launched successfully, run the `oc get csv` command. In the command output, if the value of the `PHASE` column is `Succeeded`, the operator launched successfully:
+
[source,bash,options="nowrap"]
----
$ oc get csv

NAME                                DISPLAY                                         VERSION   REPLACES                            PHASE
grafana-operator.v3.10.3            Grafana Operator                                3.10.3    grafana-operator.v3.10.2            Succeeded
...
----

. To launch a Grafana instance, create or modify the `ServiceTelemetry` object. Set `graphing.enabled` and `graphing.grafana.ingressEnabled` to `true`.
+
[source,bash]
----
$ oc edit stf default

apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
...
spec:
  ...
  graphing:
    enabled: true
    grafana:
      ingressEnabled: true
----

. Verify that the Grafana instance deployed:
+
[source,bash]
----
$ oc get pod -l app=grafana

NAME                                  READY   STATUS    RESTARTS   AGE
grafana-deployment-7fc7848b56-sbkhv   1/1     Running   0          1m
----

. Verify that the Grafana data sources installed correctly:
+
[source,bash]
----
$ oc get grafanadatasources

NAME                    AGE
default-datasources     20h
----

. Verify that the Grafana route exists:
+
[source,bash,options="nowrap"]
----
$ oc get route grafana-route

NAME            HOST/PORT                                          PATH   SERVICES          PORT   TERMINATION   WILDCARD
grafana-route   grafana-route-service-telemetry.apps.infra.watch          grafana-service   3000   edge          None
----

. The dashboards in {ProjectShort} require features that are only available in Grafana version 8.1.0 and later. Ensure that you have the correct version of Grafana:
+
[source,bash]
----
$ oc get pod -l "app=grafana" -ojsonpath='{.items[0].spec.containers[0].image}'

docker.io/grafana/grafana:7.3.10
----

. If the running image is older than 8.1.0, patch the Grafana object to update the image:
+
[source,bash,options="nowrap"]
----
$ oc patch grafana/default --type merge -p '{"spec":{"baseImage":"docker.io/grafana/grafana:8.1.0"}}'
----
+
The Grafana deployment restarts.

. Verify that a new Grafana pod exists and has a `STATUS` value of `Running`:
+
[source,bash,options="nowrap"]
----
$ oc get pod -l "app=grafana"
NAME                                 READY     STATUS    RESTARTS   AGE
grafana-deployment-fb9799b58-j2hj2   1/1       Running   0          10s
----

. Verify that the new instance is running the updated image:
+
[source,bash,options="nowrap"]
----
$ oc get pod -l "app=grafana" -ojsonpath='{.items[0].spec.containers[0].image}'
docker.io/grafana/grafana:8.1.0
----
