[id="monitoring-container-health-and-api-status_{context}"]
= Monitoring container health and API status

[role="_abstract"]
You can use the OCI (Open Container Initiative) standard to assess the container health status of each {OpenStack} ({OpenStackShort}) service by periodically running a health check script. Most {OpenStackShort} services implement a health check that logs issues and returns a binary status. For the {OpenStackShort} APIs, the health checks query the root endpoint and determine the health based on the response time.

To monitor healthchecks in {Project} ({ProjectShort}), you must enable and configure the `collectd-sensubility` plugin to work with the `amqp1` protocol and configure the the amqp1 address. Container health monitoring is enabled by default in `enable-stf.yaml`. For more information, see xref:creating-the-base-configuration-for-stf_assembly-completing-the-stf-configuration[].

.Prerequisites

* You have created the `stf-connectors.yaml` file in your templates directory. For more information, see xref:configuring-red-hat-openstack-platform-overcloud-for-stf_assembly-completing-the-stf-configuration[].

* You are using the most current version of {OpenStack} {OpenStackVersion}.

.Procedure

To disable the monitoring of container health status disable `CollectdEnableSensubility`.

. Open the `stf-connectors.yaml` and add the `CollectdEnableSensubility` parameter to override the setting in `enable-stf.yaml`:
+
[source,yaml]
----
CollectdEnableSensubility: false
----

. Continue with the overcloud deployment procedure. For more information, see xref:deploying-the-overcloud_assembly-completing-the-stf-configuration[].

.Additional resources

* For more information about multiple cloud addresses, see xref:configuring-multiple-clouds_assembly-completing-the-stf-configuration[].
