// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_configuring-red-hat-openstack-platform-overcloud-for-stf.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="configuring-red-hat-openstack-platform-overcloud-for-stf_{context}"]
= Configuring {OpenStack} overcloud for {Project}

To configure the {OpenStack} overcloud, you must configure the data collection applications and the data transport to {ProjectShort}, and deploy the overcloud.

To configure the {OpenStack} overcloud, complete the following tasks:

. xref:retrieving-the-qdr-route-address[]
. xref:configuring-the-stf-connection-for-the-overcloud[]
. xref:validating-clientside-installation_completing-the-stf-configuration[]

[[retrieving-the-qdr-route-address]]
== Retrieving the {MessageBus} route address

When you configure the {OpenStack} overcloud for {ProjectShort}, you must provide the {MessageBus} route address in the {ProjectShort} connection file.

.Procedure

. Log in to your {OpenShift} ({OpenShiftShort}) environment.
//subs="+quotes"
. In the `service-telemetry` project, retrieve the {MessageBus} route address:
+
[options="nowrap", subs="verbatim"]
----
$ oc get routes -ogo-template='{{ range .items }}{{printf "%s\n" .spec.host }}{{ end }}' | grep "\-5671"
stf-default-interconnect-5671-service-telemetry.apps.infra.watch
----
+
[NOTE:]
If your {ProjectShort} installation differs from the documentation, ensure that you retrieve the correct {MessageBus} route address. 

[[configuring-the-stf-connection-for-the-overcloud]]
== Configuring the {ProjectShort} connection for the overcloud

To configure the {ProjectShort} connection, you must create a file that contains the connection configuration of the {MessageBus} for the overcloud to the {ProjectShort} deployment. Enable the collection of events and storage of the events in {ProjectShort} and deploy the overcloud.

.Procedure

. Log in to the {OpenStack} undercloud as the `stack` user.

. Create a configuration file called `stf-connectors.yaml` in the `/home/stack` directory.
+
IMPORTANT: The Service Telemetry Operator simplifies the deployment of all data ingestion and data storage components for single cloud deployments. To share the data storage domain with multiple clouds, see xref:configuring-multiple-clouds_advanced-features[].

. In the `stf-connectors.yaml` file, configure the `MetricsQdrConnectors` address to connect the {MessageBus} on the overcloud to the {ProjectShort} deployment.
* Add the `CeilometerQdrPublishEvents: true` parameter to enable collection and transport of Ceilometer events to {ProjectShort}.
* Replace the `host` parameter with the value of `HOST/PORT` that you retrieved in xref:retrieving-the-qdr-route-address[]:
+
ifdef::include_when_13[]
[source,yaml]
----
parameter_defaults:
    EventPipelinePublishers: []
    CeilometerEnablePanko: false
    CeilometerQdrPublishEvents: true
    CollectdAmqpInstances:
        notify:
            format: JSON
            notify: true
            presettle: false
        telemetry:
            format: JSON
            presettle: false
    CollectdAmqpInterval: 5
    CollectdConnectionType: amqp1
    CollectdDefaultPlugins:
    - cpu
    - df
    - load
    - connectivity
    - intel_rdt
    - ipmi
    - procevent
    CollectdDefaultPollingInterval: 5
    MetricsQdrAddresses:
    -   distribution: multicast
        prefix: collectd
    -   distribution: multicast
        prefix: anycast/ceilometer
    MetricsQdrConnectors:
    -   host: stf-default-interconnect-5671-service-telemetry.apps.infra.watch
        port: 443
        role: edge
        sslProfile: sslProfile
        verifyHostname: false
    MetricsQdrSSLProfiles:
    -   name: sslProfile
----
endif::include_when_13[]
ifdef::include_when_16[]
[source,yaml]
----
parameter_defaults:
    EventPipelinePublishers: []
    CeilometerQdrPublishEvents: true
    MetricsQdrConnectors:
    - host: stf-default-interconnect-5671-service-telemetry.apps.infra.watch
      port: 443
      role: edge
      sslProfile: sslProfile
      verifyHostname: false
----
endif::include_when_16[]

. Add the following files to your {OpenStack} {OpenStackInstaller} deployment to setup collectd and {MessageBus}:
+
* the `stf-connectors.yaml` environment file
* the `enable-stf.yaml` file that ensures that the environment is being used during the overcloud deployment
* the `ceilometer-write-qdr.yaml` file that ensures that Ceilometer telemetry is sent to {ProjectShort}
+
[options="nowrap", subs="+quotes"]
ifdef::include_when_13[]
----
openstack overcloud deploy <other arguments>
--templates /usr/share/openstack-tripleo-heat-templates \
  --environment-file <...other-environment-files...> \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/ceilometer-write-qdr.yaml \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/collectd-write-qdr.yaml \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/qdr-edge-only.yaml \
  --environment-file /home/stack/stf-connectors.yaml
----
endif::include_when_13[]
ifdef::include_when_16[]
----
openstack overcloud deploy <other arguments>
  --templates /usr/share/openstack-tripleo-heat-templates \
  --environment-file <...other-environment-files...> \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/ceilometer-write-qdr.yaml \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/enable-stf.yaml \
  --environment-file /home/stack/stf-connectors.yaml
----
endif::include_when_16[]

. Deploy the {OpenStack} overcloud.
