[id="monitoring-resource-usage-of-openstack-services_{context}"]
= Monitoring the resource usage of {OpenStack} services

[role="_abstract"]
Monitor the resource usage of the {OpenStack} ({OpenStackShort}) services, such as the APIs and other infrastructure processes, to identify bottlenecks in the overcloud by showing services that run out of compute power. Enable the `collectd-libpod-stats` plugin to gather CPU and memory usage metrics for every container running in the overcloud.

.Prerequisites

* You have created the `stf-connectors.yaml` file. For more information, see xref:configuring-red-hat-openstack-platform-overcloud-for-stf_assembly-completing-the-stf-configuration[].
* You are using the most current version of {OpenStackShort}: {OpenStackVersion}.

.Procedure

To disable the monitoring of container resource usage, disable `CollectdEnableLibpodstats`.

. Open the `stf-connectors.yaml` file and add the `CollectdEnableLibpodstats` parameter to override the setting in `enable-stf.yaml`
+
[source,yaml]
----
  CollectdEnableLibpodstats: false
----

. Continue with the overcloud deployment procedure. For more information, see xref:deploying-the-overcloud_assembly-completing-the-stf-configuration[].
