[id="planning-amqp-address-prefixes_{context}"]
= Planning AMQP address prefixes

[role="_abstract"]

ifdef::include_when_16[]
By default, {OpenStack} ({OpenStackShort}) nodes retrieve data through two data collectors; collectd and Ceilometer. The collectd-sensubility plugin requires a unique address. These components send telemetry data or notifications to the respective AMQP addresses, for example, `collectd/telemetry`. {ProjectShort} Smart Gateways listen on those AMQP addresses for data. To support multiple clouds and to identify which cloud generated the monitoring data, configure each cloud to send data to a unique address. Add a cloud identifier prefix to the second part of the address. The following list shows some example addresses and identifiers:

* `collectd/cloud1-telemetry`
* `collectd/cloud1-notify`
* `sensubility/cloud1-telemetry`
* `anycast/ceilometer/cloud1-metering.sample`
* `anycast/ceilometer/cloud1-event.sample`
* `collectd/cloud2-telemetry`
* `collectd/cloud2-notify`
* `sensubility/cloud2-telemetry`
* `anycast/ceilometer/cloud2-metering.sample`
* `anycast/ceilometer/cloud2-event.sample`
* `collectd/us-east-1-telemetry`
* `collectd/us-west-3-telemetry`
endif::include_when_16[]

ifdef::include_when_13[]
By default, {OpenStack} nodes retrieve data through two data collectors; collectd and Ceilometer. These components send telemetry data or notifications to the respective AMQP addresses, for example, collectd/telemetry. {ProjectShort} Smart Gateways listen on the AMQP addresses for monitoring data. To support multiple clouds and to identify which cloud generated the monitoring data, configure each cloud to send data to a unique address. Add a cloud identifier prefix to the second part of the address. The following list shows some example addresses and identifiers:

* `collectd/cloud1-telemetry`
* `collectd/cloud1-notify`
* `anycast/ceilometer/cloud1-metering.sample`
* `anycast/ceilometer/cloud1-event.sample`
* `collectd/cloud2-telemetry`
* `collectd/cloud2-notify`
* `anycast/ceilometer/cloud2-metering.sample`
* `anycast/ceilometer/cloud2-event.sample`
* `collectd/us-east-1-telemetry`
* `collectd/us-west-3-telemetry`
endif::include_when_13[]
