[id="creating-a-servicetelemetry-object-in-openshift_{context}"]
= Creating a ServiceTelemetry object in {OpenShift}

[role="_abstract"]
Create a `ServiceTelemetry` object in {OpenShift} to result in the Service Telemetry Operator creating the supporting components for a {Project} ({ProjectShort}) deployment. For more information, see xref:primary-parameters-of-the-servicetelemetry-object_assembly-installing-the-core-components-of-stf[].

.Prerequisites

. You have installed {ObservabilityOperator} to allow storage of metrics. For more information, see xref:deploying-observability-operator_assembly-installing-the-core-components-of-stf[].
. You have installed cert-manager for Red Hat OpenShift to allow certificate management. For more information, see xref:deploying-certificate-manager-for-openshift-operator_assembly-installing-the-core-components-of-stf[].

.Procedure

. Log in to your {OpenShift} environment where {ProjectShort} is hosted.

. To deploy {ProjectShort} that results in the core components for metrics delivery being configured, create a `ServiceTelemetry` object:
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc apply -f - <<EOF
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: default
  namespace: service-telemetry
spec:
  alerting:
    alertmanager:
      storage:
        persistent:
          pvcStorageRequest: 20G
        strategy: persistent
    enabled: true
  backends:
    metrics:
      prometheus:
        enabled: true
        scrapeInterval: 30s
        storage:
          persistent:
            pvcStorageRequest: 20G
          retention: 24h
          strategy: persistent
  clouds:
  - metrics:
      collectors:
      - bridge:
          ringBufferCount: 15000
          ringBufferSize: 16384
          verbose: false
        collectorType: collectd
        debugEnabled: false
        subscriptionAddress: collectd/cloud1-telemetry
      - bridge:
          ringBufferCount: 15000
          ringBufferSize: 16384
          verbose: false
        collectorType: ceilometer
        debugEnabled: false
        subscriptionAddress: anycast/ceilometer/cloud1-metering.sample
      - bridge:
          ringBufferCount: 15000
          ringBufferSize: 65535
          verbose: false
        collectorType: sensubility
        debugEnabled: false
        subscriptionAddress: sensubility/cloud1-telemetry
    name: cloud1
  observabilityStrategy: use_redhat
  transports:
    qdr:
      auth: basic
      certificates:
        caCertDuration: 70080h
        endpointCertDuration: 70080h
      enabled: true
      web:
        enabled: false
EOF
----
+
To override these defaults, add the configuration to the `spec` parameter.

. View the {ProjectShort} deployment logs in the Service Telemetry Operator:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc logs --selector name=service-telemetry-operator

...
--------------------------- Ansible Task Status Event StdOut  -----------------

PLAY RECAP *********************************************************************
localhost                  : ok=90   changed=0    unreachable=0    failed=0    skipped=26   rescued=0    ignored=0
----

.Verification

* To determine that all workloads are operating correctly, view the pods and the status of each pod.
+
[source,bash,options="nowrap"]
----
$ oc get pods

NAME                                                        READY   STATUS    RESTARTS   AGE
alertmanager-default-0                                      3/3     Running   0          123m
default-cloud1-ceil-meter-smartgateway-7dfb95fcb6-bs6jl     3/3     Running   0          122m
default-cloud1-coll-meter-smartgateway-674d88d8fc-858jk     3/3     Running   0          122m
default-cloud1-sens-meter-smartgateway-9b869695d-xcssf      3/3     Running   0          122m
default-interconnect-6cbf65d797-hk7l6                       1/1     Running   0          123m
interconnect-operator-7bb99c5ff4-l6xc2                      1/1     Running   0          138m
prometheus-default-0                                        3/3     Running   0          122m
service-telemetry-operator-7966cf57f-g4tx4                  1/1     Running   0          138m
smart-gateway-operator-7d557cb7b7-9ppls                     1/1     Running   0          138m
----
