[id="configuring-the-stf-connection-for-the-overcloud_{context}"]
= Configuring the {ProjectShort} connection for the overcloud

[role="_abstract"]
To configure the {Project} ({ProjectShort}) connection, you must create a file that contains the connection configuration of the {MessageBus} for the overcloud to the {ProjectShort} deployment. Enable the collection of events and storage of the events in {ProjectShort} and deploy the overcloud. The default configuration is for a single cloud instance with the default message bus topics. For configuration of multiple cloud deployments, see xref:configuring-multiple-clouds_assembly-completing-the-stf-configuration[].

.Prerequisites

ifdef::include_when_13,include_when_17[]
* Retrieve the CA certificate from the {MessageBus} deployed by {ProjectShort}. For more information, see xref:getting-ca-certificate-from-stf-for-overcloud-configuration_assembly-completing-the-stf-configuration[].
endif::include_when_13,include_when_17[]
* Retrieve the {MessageBus} route address. For more information, see xref:retrieving-the-qdr-route-address_assembly-completing-the-stf-configuration[].

// The following configuration should match the contents in modules/proc_creating-openstack-environment-file-for-multiple-clouds.adoc. If you have changes to make, please make the same changes to both files.
.Procedure

. Log in to the {OpenStackShort} undercloud as the `stack` user.

. Create a configuration file called `stf-connectors.yaml` in the `/home/stack` directory.

ifndef::include_when_13[]
. In the `stf-connectors.yaml` file, configure the `MetricsQdrConnectors` address to connect the {MessageBus} on the overcloud to the {ProjectShort} deployment. You configure the topic addresses for Sensubility, Ceilometer, and collectd in this file to match the defaults in {ProjectShort}. For more information about customizing topics and cloud configuration, see xref:configuring-multiple-clouds_assembly-completing-the-stf-configuration[].
endif::[]
ifdef::include_when_13[]
. In the `stf-connectors.yaml` file, configure the `MetricsQdrConnectors` address to connect the {MessageBus} on the overcloud to the {ProjectShort} deployment. You configure the topic addresses for Ceilometer and collectd in this file to match the defaults in {ProjectShort}. For more information about customizing topics and cloud configuration, see xref:configuring-multiple-clouds_assembly-completing-the-stf-configuration[].
endif::[]

* The `resource_registry` configuration directly loads the collectd service because you do not include the `collectd-write-qdr.yaml` environment file for multiple cloud deployments.
* Replace the `host` parameter with the value of `HOST/PORT` that you retrieved in xref:retrieving-the-qdr-route-address_assembly-completing-the-stf-configuration[].
ifdef::include_when_13,include_when_17[]
* Replace the `caCertFileContent` parameter with the contents retrieved in xref:getting-ca-certificate-from-stf-for-overcloud-configuration_assembly-completing-the-stf-configuration[].
endif::include_when_13,include_when_17[]
* Replace the `host` sub-parameter of `MetricsQdrConnectors` with the value of `HOST/PORT` that you retrieved in xref:retrieving-the-qdr-route-address_assembly-completing-the-stf-configuration[].
* Set `CeilometerQdrEventsConfig.topic` to define the topic for Ceilometer events. The format of this value is `anycast/ceilometer/cloud1-event.sample`.
* Set `CeilometerQdrMetricsConfig.topic` to define the topic for Ceilometer metrics. The format of this value is `anycast/ceilometer/cloud1-metering.sample`.
* Set `CollectdAmqpInstances` to define the topic for collectd events. The format of this value is `collectd/cloud1-notify`.
* Set `CollectdAmqpInstances` to define the topic for collectd metrics. The format of this value is `collectd/cloud1-telemetry`.
ifndef::include_when_13[]
* Set `CollectdSensubilityResultsChannel` to define the topic for collectd-sensubility events. The format of this value is `sensubility/cloud1-telemetry`.
endif::[]
+
.stf-connectors.yaml
[source,yaml,options="nowrap"]
----
resource_registry:
  OS::TripleO::Services::Collectd: /usr/share/openstack-tripleo-heat-templates/deployment/metrics/collectd-container-puppet.yaml

parameter_defaults:
    MetricsQdrConnectors:
        - host: stf-default-interconnect-5671-service-telemetry.apps.infra.watch
          port: 443
          role: edge
          verifyHostname: false
          sslProfile: sslProfile

    MetricsQdrSSLProfiles:
        - name: sslProfile
ifdef::include_when_13,include_when_17[]
          caCertFileContent: |
            -----BEGIN CERTIFICATE-----
            <snip>
            -----END CERTIFICATE-----
endif::include_when_13,include_when_17[]

    CeilometerQdrEventsConfig:
        driver: amqp
        topic: cloud1-event

    CeilometerQdrMetricsConfig:
        driver: amqp
        topic: cloud1-metering

    CollectdAmqpInstances:
        cloud1-notify:
            notify: true
            format: JSON
            presettle: false
        cloud1-telemetry:
            format: JSON
            presettle: false

ifndef::include_when_13[]
    CollectdSensubilityResultsChannel: sensubility/cloud1-telemetry
endif::[]
----
