[id="retrieving-the-qdr-password_{context}"]
= Retrieving the {MessageBus} password

[role="_abstract"]
When you configure the {OpenStack} ({OpenStackShort}) overcloud for {Project} ({ProjectShort}), you must provide the {MessageBus} password in the {ProjectShort} connection file.

Basic authentication on the {MessageBus} connection can be disabled by setting `transports.qdr.auth` parameter of the STF spec to `none`. Versions of {ProjectShort} before 1.5.3 did not support this parameter and always behave as if it is set to `none`. This behaviour is preserved after an upgrade to {ProjectShort} 1.5.3 until a user explicitly changes the parameter to `basic`. New installs of {ProjectShort} 1.5.3 or later use `basic` authentication by default.

.Procedure

. Log in to your {OpenShift} environment where {ProjectShort} is hosted.

. Change to the `service-telemetry` project:
+
[source,bash]
----
$ oc project service-telemetry
----

. Retrieve the {MessageBus} password:
+
[source,bash,options="nowrap",subs="verbatim"]
----
$ oc get secret default-interconnect-users -o json | jq -r .data.guest | base64 -d
----
