// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_configuring-red-hat-openstack-platform-overcloud-for-stf.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="configuring-red-hat-openstack-platform-overcloud-for-stf_{context}"]
= Configuring {OpenStack} overcloud for {ProjectShort}

To configure the {OpenStack} overcloud, you must configure collectd and {MessageBus}:

. Create a file and name it `stf-connectors.yaml`. Save the file in the `/home/stack` directory.
. Retrieve the QDR route address for the `MetricsQdrConnectors` host parameter. For more information, see Retrieving the QDR route address.
. In the `stf-connectors.yaml` file, configure the `MetricsQdrConnectors` address to connect the Apache Qpid Dispatch Router bus on the overcloud to the STF deployment. The following sample is from the `stf-connectors.yaml` environment file:
+
----
parameter_defaults:
    MetricsQdrConnectors:
  - host: qdr-white-port-5671-service-telemetry.apps.service-telemetry.tld
    port: 443
    role: edge
    sslProfile: sslProfile
    verifyHostname: false
  MetricsQdrSSLProfiles:
  - name: sslProfile
----

. Add the `stf-connectors.yaml` environment file to a {OpenStack}{OpenStackInstaller} deployment to configure and setup collectd and {MessageBus}. Add the `enable-stf.yaml` file to the deployment to ensure that the environment is being used during the overcloud deployment:
+
----
openstack overcloud deploy <other arguments>
-e /usr/share/openstack-tripleo-heat-templates/environments/enable-stf.yaml
-e /home/stack/stf-connectors.yaml
-e <other-environment-files>
     <other configuration files>
----
