// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_deploying-stf-to-the-openshift-environment.adoc[leveloffset=+1]


[id="deploying-stf-to-the-openshift-environment_{context}"]
= Deploying {ProjectShort} to the {OpenShiftShort} environment

[role="_abstract"]
You can deploy {ProjectShort} to the {OpenShiftShort} environment in one of two ways:


* Deploy {ProjectShort} and store events with ElasticSearch. For more information, see xref:deploying-stf-to-the-openshift-environment-with-elasticsearch[].
* Deploy {ProjectShort} without ElasticSearch and disable events support. For more information, see xref:deploying-stf-to-the-openshift-environment-without-elasticsearch[].

[id="deploying-stf-to-the-openshift-environment-with-elasticsearch"]
== Deploying {ProjectShort} to the {OpenShiftShort} environment with ElasticSearch

Complete the following tasks:

. xref:creating-a-namespace[].
. xref:creating-an-operatorgroup[].
. xref:enabling-the-operatorhubio-community-catalog-source[].
ifeval::["{build}" == "upstream"]
. xref:enabling-the-infrawatch-catalog-source[].
endif::[]
. xref:subscribing-to-the-amq-certificate-manager-operator[].
. xref:subscribing-to-elastic-cloud-on-kubernetes-operator[].
. xref:subscribing-to-the-service-telemetry-operator[].
. xref:creating-a-servicetelemetry-object-in-openshift_assembly-installing-the-core-components-of-stf[].

[id="deploying-stf-to-the-openshift-environment-without-elasticsearch"]
== Deploying {ProjectShort} to the {OpenShiftShort} environment without ElasticSearch

Complete the following tasks:

. xref:creating-a-namespace[].
. xref:creating-an-operatorgroup[].
ifeval::["{build}" == "upstream"]
. xref:enabling-the-infrawatch-catalog-source[].
endif::[]
. xref:subscribing-to-the-amq-certificate-manager-operator[].
. xref:subscribing-to-the-service-telemetry-operator[].
. xref:creating-a-servicetelemetry-object-in-openshift_assembly-installing-the-core-components-of-stf[].


[id="creating-a-namespace"]
== Creating a namespace

Create a namespace to hold the {ProjectShort} components. The `service-telemetry` namespace is used throughout the documentation:

.Procedure

* Enter the following command:
+
[source,bash]
----
$ oc new-project service-telemetry
----

[id="creating-an-operatorgroup"]
== Creating an OperatorGroup

Create an OperatorGroup in the namespace so that you can schedule the Operator pods.

.Procedure

* Enter the following command:
+
[source,bash]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: service-telemetry-operator-group
  namespace: service-telemetry
spec:
  targetNamespaces:
  - service-telemetry
EOF
----

.Additional resources

For more information, see https://docs.openshift.com/container-platform/{SupportedOpenShiftVersion}/operators/understanding_olm/olm-understanding-operatorgroups.html[OperatorGroups].

[id="enabling-the-operatorhubio-community-catalog-source"]
== Enabling the OperatorHub.io Community Catalog Source

Before you install ElasticSearch, you must have access to the resources on the OperatorHub.io Community Catalog Source:

.Procedure

* Enter the following command:
+
[source,bash]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/operator-framework/upstream-community-operators:latest
  displayName: OperatorHub.io Operators
  publisher: OperatorHub.io
EOF
----

//upstream only

ifeval::["{build}" == "upstream"]
[id="enabling-the-infrawatch-catalog-source"]
== Enabling InfraWatch Catalog Source

Before you deploy {ProjectShort} on {OpenShift}, you must enable the catalog source.

.Procedure

. Install a CatalogSource that contains the Service Telemetry Operator and the Smart Gateway Operator:
+


[source,bash]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: infrawatch-operators
  namespace: openshift-marketplace
spec:
  displayName: InfraWatch Operators
  image: quay.io/infrawatch-operators/infrawatch-catalog:latest
  publisher: InfraWatch
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m
EOF
----


. To validate the creation of your CatalogSource, use the `oc get catalogsources` command:
+

[source,bash,options="nowrap",subs="+quotes"]
----
$ oc get -nopenshift-marketplace catalogsource infrawatch-operators

NAME                   DISPLAY                TYPE   PUBLISHER    AGE
infrawatch-operators   InfraWatch Operators   grpc   InfraWatch   2m16s
----



. To validate that the Operators are available from the catalog, use the `oc get packagemanifest` command:
+

[source,bash,options="nowrap",subs="+quotes"]
----
$ oc get packagemanifests | grep InfraWatch

service-telemetry-operator                    InfraWatch Operators       7m20s
smart-gateway-operator                        InfraWatch Operators       7m20s
----
endif::[]

[id="subscribing-to-the-amq-certificate-manager-operator"]
== Subscribing to the AMQ Certificate Manager Operator

You must subscribe to the AMQ Certificate Manager Operator before you deploy the other {ProjectShort} components because the AMQ Certificate Manager Operator runs globally-scoped. The AMQ Certificate Manager Operator is not compatible with the dependency management of Operator Lifecycle Manager when you use it with other namespace-scoped operators.

.Procedure

. Subscribe to the AMQ Certificate Manager Operator, create the subscription, and validate the AMQ7 Certificate Manager:
+
[NOTE]
The AMQ Certificate Manager is installed globally for all namespaces, so the `namespace` value provided is `openshift-operators`. You might not see your `amq7-cert-manager.v1.0.0` ClusterServiceVersion in the `service-telemetry` namespace for a few minutes until the processing executes against the namespace.

+
[source,bash]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq7-cert-manager
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: amq7-cert-manager
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----

. To validate your `ClusterServiceVersion`, use the `oc get csv` command:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc get --namespace openshift-operators csv

NAME                       DISPLAY                                         VERSION   REPLACES   PHASE
amq7-cert-manager.v1.0.0   Red Hat Integration - AMQ Certificate Manager   1.0.0                Succeeded
----
+
Ensure that amq7-cert-manager.v1.0.0 has a phase `Succeeded`.

[id="subscribing-to-elastic-cloud-on-kubernetes-operator"]
== Subscribing to the Elastic Cloud on Kubernetes Operator

Before you install the Service Telemetry Operator and if you plan to store events in ElasticSearch, you must enable the Elastic Cloud Kubernetes Operator.

.Procedure

. Apply the following manifest to your {OpenShiftShort} environment to enable the Elastic Cloud on Kubernetes Operator:
+
[source,bash]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elastic-cloud-eck
  namespace: service-telemetry
spec:
  channel: stable
  installPlanApproval: Automatic
  name: elastic-cloud-eck
  source: operatorhubio-operators
  sourceNamespace: openshift-marketplace
EOF
----

. To verify that the `ClusterServiceVersion` for ElasticSearch Cloud on Kubernetes `succeeded`, enter the `oc get csv` command:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc get csv

NAME                       DISPLAY                                         VERSION   REPLACES   PHASE
elastic-cloud-eck.v1.2.1   Elastic Cloud on Kubernetes                     1.2.1                Succeeded
----

[id="subscribing-to-the-service-telemetry-operator"]
== Subscribing to the Service Telemetry Operator

You must subscribe to the Service Telemetry Operator, which manages the {ProjectShort} instances.

.Procedure

. To create the Service Telemetry Operator subscription, enter the `oc apply -f` command:
+
ifeval::["{build}" == "upstream"]
[source,bash]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-telemetry-operator
  namespace: service-telemetry
spec:
  channel: stable-1.2
  installPlanApproval: Automatic
  name: service-telemetry-operator
  source: infrawatch-operators
  sourceNamespace: openshift-marketplace
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
[source,bash]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-telemetry-operator
  namespace: service-telemetry
spec:
  channel: stable-1.2
  installPlanApproval: Automatic
  name: service-telemetry-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----
endif::[]


. To validate the Service Telemetry Operator and the dependent operators, enter the following command:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc get csv --namespace service-telemetry

NAME                                DISPLAY                                         VERSION   REPLACES   PHASE
amq7-cert-manager.v1.0.0            Red Hat Integration - AMQ Certificate Manager   1.0.0                Succeeded
amq7-interconnect-operator.v1.2.3   Red Hat Integration - AMQ Interconnect          1.2.3                Succeeded
elastic-cloud-eck.v1.4.0            Elasticsearch (ECK) Operator                    1.4.0                Succeeded
grafana-operator.v3.9.0             Grafana Operator                                3.9.0                Succeeded
prometheusoperator.0.37.0           Prometheus Operator                             0.37.0               Succeeded
service-telemetry-operator.v1.2.1   Service Telemetry Operator                      1.2.1                Succeeded
smart-gateway-operator.v2.2.1       Smart Gateway Operator                          2.2.1                Succeeded
----
