// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_updating-collectd-configuration.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="creating-openstack-environment-file_{context}"]
= Creating the OpenStack environment file

To label traffic according to the cloud of origin, you must create a configuration with cloud-specific instance names. Create an `stf-connectors.yaml` file and adjust the values of `CeilometerQdrEventsConfig`, `CeilometerQdrMetricsConfig` and `CollectdAmqpInstances` to match the AMQP address prefix scheme. For more information, see xref:planning-amqp-address-prefixes_advanced-features[].


[WARNING]
Remove
ifdef::include_when_16[]
`enable-stf.yaml` and
endif::include_when_16[]
`ceilometer-write-qdr.yaml` environment file references from your overcloud deployment. This configuration is redundant and results in duplicate information being sent from each cloud node.

.Procedure

. Create the `stf-connectors.yaml` file and modify it to match the AMQP address that you want for this cloud deployment:
+
.stf-connectors.yaml
ifdef::include_when_13[]
+
[source,yaml,options="nowrap"]
----
resource_registry:
    OS::TripleO::Services::Collectd: /usr/share/openstack-tripleo-heat-templates/docker/services/metrics/collectd.yaml
    OS::TripleO::Services::MetricsQdr: /usr/share/openstack-tripleo-heat-templates/docker/services/metrics/qdr.yaml
    OS::TripleO::Services::CeilometerAgentCentral: /usr/share/openstack-tripleo-heat-templates/docker/services/ceilometer-agent-central.yaml
    OS::TripleO::Services::CeilometerAgentNotification: /usr/share/openstack-tripleo-heat-templates/docker/services/ceilometer-agent-notification.yaml
    OS::TripleO::Services::CeilometerAgentIpmi: /usr/share/openstack-tripleo-heat-templates/docker/services/ceilometer-agent-ipmi.yaml
    OS::TripleO::Services::ComputeCeilometerAgent: /usr/share/openstack-tripleo-heat-templates/docker/services/ceilometer-agent-compute.yaml
    OS::TripleO::Services::Redis: /usr/share/openstack-tripleo-heat-templates/docker/services/pacemaker/database/redis.yaml

parameter_defaults:
    EventPipelinePublishers: []
    MetricPipelinePublishers: []
    CeilometerEnablePanko: false
    CeilometerQdrPublishEvents: true
    CeilometerQdrPublishMetrics: true
    CeilometerQdrEventsConfig:
        driver: amqp
        topic: cloud1-event   # <1>
    CeilometerQdrMetricsConfig:
        driver: amqp
        topic: cloud1-metering   # <2>

    CollectdConnectionType: amqp1
    CollectdAmqpInterval: 5
    CollectdDefaultPollingInterval: 5
    CollectdDefaultPlugins:
        - cpu
        - df
        - disk
        - hugepages
        - interface
        - load
        - memory
        - processes
        - unixsock
        - uptime
        - connectivity
        - intel_rdt
        - ipmi
        - procevent

    CollectdAmqpInstances:
        cloud1-notify:        # <3>
            notify: true
            format: JSON
            presettle: false
        cloud1-telemetry:     # <4>
            format: JSON
            presettle: false

    MetricsQdrAddresses:
        - prefix: collectd
          distribution: multicast
        - prefix: anycast/ceilometer
          distribution: multicast

    MetricsQdrSSLProfiles:
        - name: sslProfile

    MetricsQdrConnectors:
        - host: stf-default-interconnect-5671-service-telemetry.apps.infra.watch   # <5>
          port: 443
          role: edge
          verifyHostname: false
          sslProfile: sslProfile

    ExtraConfig:
        collectd::plugin::cpu::reportbycpu: true
        collectd::plugin::cpu::reportbystate: true
        collectd::plugin::cpu::reportnumcpu: false
        collectd::plugin::cpu::valuespercentage: true
        collectd::plugin::df::ignoreselected: true
        collectd::plugin::df::reportbydevice: true
        collectd::plugin::df::fstypes: ['xfs']
        collectd::plugin::load::reportrelative: true
        collectd::plugin::virt::connection: "qemu:///system"
        collectd::plugin::virt::extra_stats: "cpu_util disk disk_err pcpu job_stats_background perf vcpupin"
        collectd::plugin::virt::hostname_format: "hostname"
----
endif::include_when_13[]
ifdef::include_when_16[]
+
[source,yaml,options="nowrap"]
----
resource_registry:
    OS::TripleO::Services::Collectd: /usr/share/openstack-tripleo-heat-templates/deployment/metrics/collectd-container-puppet.yaml
    OS::TripleO::Services::MetricsQdr: /usr/share/openstack-tripleo-heat-templates/deployment/metrics/qdr-container-puppet.yaml
    OS::TripleO::Services::CeilometerAgentCentral: /usr/share/openstack-tripleo-heat-templates/deployment/ceilometer/ceilometer-agent-central-container-puppet.yaml
    OS::TripleO::Services::CeilometerAgentNotification: /usr/share/openstack-tripleo-heat-templates/deployment/ceilometer/ceilometer-agent-notification-container-puppet.yaml
    OS::TripleO::Services::CeilometerAgentIpmi: /usr/share/openstack-tripleo-heat-templates/deployment/ceilometer/ceilometer-agent-ipmi-container-puppet.yaml
    OS::TripleO::Services::ComputeCeilometerAgent: /usr/share/openstack-tripleo-heat-templates/deployment/ceilometer/ceilometer-agent-compute-container-puppet.yaml
    OS::TripleO::Services::Redis: /usr/share/openstack-tripleo-heat-templates/deployment/database/redis-pacemaker-puppet.yaml

parameter_defaults:
    EnableSTF: true

    EventPipelinePublishers: []
    MetricPipelinePublishers: []
    CeilometerEnablePanko: false
    CeilometerQdrPublishEvents: true
    CeilometerQdrEventsConfig:
        driver: amqp
        topic: cloud1-event   # <1>
    CeilometerQdrMetricsConfig:
        driver: amqp
        topic: cloud1-metering   # <2>


    CollectdConnectionType: amqp1
    CollectdAmqpInterval: 5
    CollectdDefaultPollingInterval: 5

    CollectdAmqpInstances:
        cloud1-notify:        # <3>
            notify: true
            format: JSON
            presettle: false
        cloud1-telemetry:     # <4>
            format: JSON
            presettle: true

    MetricsQdrAddresses:
        - prefix: collectd
          distribution: multicast
        - prefix: anycast/ceilometer
          distribution: multicast

    MetricsQdrSSLProfiles:
        - name: sslProfile

    MetricsQdrConnectors:
        - host: stf-default-interconnect-5671-service-telemetry.apps.infra.watch   # <5>
          port: 443
          role: edge
          verifyHostname: false
          sslProfile: sslProfile
----
endif::include_when_16[]
<1> Define the topic for Ceilometer events. This value is the address format of `anycast/ceilometer/cloud1-event.sample`.
<2> Define the topic for Ceilometer metrics. This value is the address format of `anycast/ceilometer/cloud1-metering.sample`.
<3> Define the topic for collectd events. This value is the format of `collectd/cloud1-notify`.
<4> Define the topic for collectd metrics. This value is the format of `collectd/cloud1-telemetry`.
<5> Adjust the `MetricsQdrConnectors` host to the address of the {ProjectShort} route.
+
. Ensure that the naming convention in the `stf-connectors.yaml` file aligns with the `spec.amqpUrl` field in the Smart Gateway configuration. For example, configure the `CeilometerQdrEventsConfig.topic` field to a value of `cloud1-event`.

. Save the file in a directory for custom environment files, for example `/home/stack/custom_templates/`.

. Source the authentication file:
+
[source,bash]
----
[stack@undercloud-0 ~]$ source stackrc

(undercloud) [stack@undercloud-0 ~]$
----

. Include the `stf-connectors.yaml` file in the `overcloud deployment` command, along with any other environment files relevant to your environment:
+
[source,bash]
----
(undercloud) [stack@undercloud-0 ~]$ openstack overcloud deploy \
--templates /usr/share/openstack-tripleo-heat-templates \
...
-e /home/stack/custom_templates/stf-connectors.yaml \
...
----


.Additional resources

For information about validating the deployment, see xref:validating-clientside-installation_completing-the-stf-configuration[].
