[id="configuring-tls-certificates-duration_{context}"]
= Configuring TLS certificates duration

[role="_abstract"]
You can configure the duration of the TLS certificates to use with {Project} ({ProjectShort}) to fit your deployment needs.
For this purpose, modify the `ServiceTelemetry` object and configure the `certificates` parameter.

.Prerequisites

* Verify you don't have an instance of Service Telemetry Operator already deployed.

NOTE:: Once created the `ServiceTelemetry` object, the required certificates and their secrets for {Project} ({ProjectShort}) are created.
In order to modify these you must follow a procedure similar to the one present in xref:xref:assembly-renewing-the-amq-interconnect-certificate_assembly[].
The following procedure is valid for greenfield {Project} ({ProjectShort}) deployments.

.Procedure

+
To override the duration of the TLS certificates, define which certificate you want to override.
In this example, set Elasticsearch endpoint certificates duration to 3 years by setting `endpointCertDuration` to `26280h`
and set QDR CA Certificates duration to 10 years by setting `caCertDuration` to `87600h`.
Keep the default for the other certificates (CA certificates for Elasticsearch and endpoint certificates for QDR will keep the value of 8 years):
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc apply -f - <<EOF
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: default
  namespace: service-telemetry
spec:
  backends:
    events:
      elasticsearch:
        enabled: true
        certificates:
          endpointCertDuration: 26280h
  transport:
    qdr:
      enabled: true
      certificates:
        caCertDuration: 87600h
EOF
----

.Verification

. Verify that the desired expiry date appears in the certificates:
+
[source,bash,options="nowrap"]
----
$ oc get secret elasticsearch-es-cert -o jsonpath='{.data.tls\.crt}' | base64 -d  | openssl x509 -in - -text | grep "Not After"
            Not After : Mar  9 21:00:16 2026 GMT

$ oc get secret  default-interconnect-selfsigned -o jsonpath='{.data.tls\.crt}' | base64 -d  | openssl x509 -in - -text | grep "Not After"
            Not After : Mar  9 21:00:16 2033 GMT
----