// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_configuring-red-hat-openstack-platform-overcloud-for-stf.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="configuring-red-hat-openstack-platform-overcloud-for-stf_{context}"]
= Configuring {OpenStack} overcloud for {ProjectShort}

To configure the {OpenStack} overcloud, you must configure the data collection applications and the data transport to {ProjectShort}:

. Retrieve the {MessageBus} route address for the `MetricsQdrConnectors` host parameter in `stf-connectors.yaml`. For more information, see <<retrieving-the-qdr-route-address>>.
. Log in to the {OpenStack} undercloud. Create a file and name it `stf-connectors.yaml`. For more information, see <<creating-stf-connectors>>.
. Run the overcloud deployment command and include the stf-connectors.yaml file, as well as any other environment files relevant to your deployment. For more information, see <<deploying-the-overcloud>>.
. Validate the client-side installation. For more information, see <<validating-clientside-installation_completing-the-stf-configuration>>.

[[retrieving-the-qdr-route-address]]
== Retrieving the {MessageBus} route address

When you configure the {OpenStack} overcloud for {ProjectShort}, you must provide the {MessageBus} route address for the `MetricsQdrConnectors` host parameter:

. Log in to your {OpenShift} environment.

.  Run the `oc get routes` command in the `service-telemetry` project:
+
----
oc get routes
NAME                             HOST/PORT                                                                                        PATH   SERVICES                   PORT    TERMINATION        WILDCARD
stf-default-interconnect-55671   stf-default-interconnect-55671-service-telemetry.apps.infra.watch          stf-default-interconnect   55671   passthrough/None   None
stf-default-interconnect-5671    stf-default-interconnect-5671-service-telemetry.apps.infra.watch           stf-default-interconnect   5671    passthrough/None   None
stf-default-interconnect-8672    stf-default-interconnect-8672-service-telemetry.apps.infra.watch           stf-default-interconnect   8672    edge/Redirect      None
----
+
Note the value in the `HOST/PORT` column for the `stf-default-interconnect-5671` route.

[[creating-stf-connectors]]
== Creating the {ProjectShort} connection file
Create a file in which you configure the connection of the {MessageBus} on the overcloud to the {ProjectShort} deployment, and enable collection of events and storage of the events in {ProjectShort}:

. Log in to the {OpenStack} undercloud as the `stack` user.

. Create a configuration file and name it `stf-connectors.yaml` in `/home/stack`.

. In the `stf-connectors.yaml` file, configure the `MetricsQdrConnectors` address to connect the {MessageBus} on the overcloud to the {ProjectShort} deployment. Add the `CeilometerQdrPublishEvents: true` parameter if you want to enable collection and transport of Ceilometer events to {ProjectShort}. Replace the `host` parameter with the value that you retrieved in <<retrieving-the-qdr-route-address>>:
+
----
parameter_defaults:
    CeilometerQdrPublishEvents: true
    MetricsQdrConnectors:
    - host: stf-default-interconnect-5671-service-telemetry.apps.infra.watch
      port: 443
      role: edge
      sslProfile: sslProfile
      verifyHostname: false
----

[[deploying-the-overcloud]]
== Deploying the overcloud

From the {OpenStack} undercloud, update the `openstack overcloud deploy` command to include the prerequisite environment files along with `stf-connectors.yaml`:

. Add the `stf-connectors.yaml` environment file to a {OpenStack} {OpenStackInstaller} deployment to configure and setup collectd and {MessageBus}. Add the `enable-stf.yaml` file to the deployment to ensure that the environment is being used during the overcloud deployment. Add the `ceilometer-write-qdr.yaml` file to the deployment to ensure that Ceilometer telemetry is sent to {ProjectShort}:
+
----
openstack overcloud deploy <other arguments>
--templates /usr/share/openstack-tripleo-heat-templates \
  --environment-file <...other-environment-files...> \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/ceilometer-write-qdr.yaml \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/enable-stf.yaml \
  --environment-file /home/stack/stf-connectors.yaml
----

. Deploy the {OpenStack} overcloud.
