[id="deploying-stf-to-the-openshift-environment_{context}"]
= Deploying {Project} to the {OpenShift} environment

[role="_abstract"]
Deploy {Project} ({ProjectShort}) to collect, store, and monitor events:



.Procedure

. Create a namespace to contain the {ProjectShort} components, for example, `service-telemetry`:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc new-project service-telemetry
----
. Create an OperatorGroup in the namespace so that you can schedule the Operator pods:
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: service-telemetry-operator-group
  namespace: service-telemetry
spec:
  targetNamespaces:
  - service-telemetry
EOF
----
+
For more information, see https://docs.openshift.com/container-platform/{NextSupportedOpenShiftVersion}/operators/understanding/olm/olm-understanding-operatorgroups.html[OperatorGroups].

ifeval::["{build}" == "upstream"]

. Before you deploy {ProjectShort} on {OpenShift}, you must enable the catalog source. Install a CatalogSource that contains the Service Telemetry Operator and the Smart Gateway Operator:
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: infrawatch-operators
  namespace: openshift-marketplace
spec:
  displayName: InfraWatch Operators
  image: quay.io/infrawatch-operators/infrawatch-catalog:nightly
  publisher: InfraWatch
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m
EOF
----

. Validate the creation of your CatalogSource:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc get -nopenshift-marketplace catalogsource infrawatch-operators

NAME                   DISPLAY                TYPE   PUBLISHER    AGE
infrawatch-operators   InfraWatch Operators   grpc   InfraWatch   2m16s
----

. Validate that the Operators are available from the catalog:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc get packagemanifests | grep InfraWatch

service-telemetry-operator                    InfraWatch Operators       7m20s
smart-gateway-operator                        InfraWatch Operators       7m20s
----
endif::[]

. Enable the OperatorHub.io Community Catalog Source to install data storage and visualization Operators:
+
[WARNING]
Red Hat supports the core Operators and workloads, including {MessageBus}, AMQ Certificate Manager, Service Telemetry Operator, and Smart Gateway Operator. Red Hat does not support the community Operators or workload components, inclusive of ElasticSearch, Prometheus, Grafana, and their Operators.
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/operatorhubio/catalog:latest
  displayName: OperatorHub.io Operators
  publisher: OperatorHub.io
EOF
----

. Subscribe to the AMQ Certificate Manager Operator by using the redhat-operators CatalogSource:
+
[NOTE]
The AMQ Certificate Manager deploys to the `openshift-operators` namespace and is then available to all namespaces across the cluster. As a result, on clusters with a large number of namespaces, it can take several minutes for the Operator to be available in the `service-telemetry` namespace. The AMQ Certificate Manager Operator is not compatible with the dependency management of Operator Lifecycle Manager when you use it with other namespace-scoped operators.
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq7-cert-manager-operator
  namespace: openshift-operators
spec:
  channel: 1.x
  installPlanApproval: Automatic
  name: amq7-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----

. Validate your ClusterServiceVersion. Ensure that amq7-cert-manager.v1.0.1 displays a phase of `Succeeded`:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc get --namespace openshift-operators csv

NAME                       DISPLAY                                         VERSION   REPLACES   PHASE
...
amq7-cert-manager.v1.0.1   Red Hat Integration - AMQ Certificate Manager   1.0.1                Succeeded
...
----

. Subscribe to the AMQ Interconnect Operator by using the redhat-operators CatalogSource:
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq7-interconnect-operator
  namespace: service-telemetry
spec:
  channel: 1.10.x
  installPlanApproval: Automatic
  name: amq7-interconnect-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
----

. Validate your ClusterServiceVersion. Ensure that amq7-interconnect-operator.v1.10.3 displays a phase of `Succeeded`:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc get csv

NAME                               DISPLAY                                 VERSION   REPLACES                           PHASE
...
amq7-interconnect-operator.v1.10.3 Red Hat Integration - AMQ Interconnect  1.10.3    amq7-interconnect-operator.v1.10.2 Succeeded
...
----

. If you plan to store metrics in Prometheus, you must enable the Prometheus Operator. To enable the Prometheus Operator, create the following manifest in your {OpenShift} environment:
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  namespace: service-telemetry
spec:
  channel: beta
  installPlanApproval: Automatic
  name: prometheus
  source: operatorhubio-operators
  sourceNamespace: openshift-marketplace
EOF
----

. Verify that the ClusterServiceVersion for Prometheus `Succeeded`:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc get csv

NAME                          DISPLAY              VERSION   REPLACES                    PHASE
...
prometheusoperator.0.47.0     Prometheus Operator  0.47.0    prometheusoperator.0.37.0   Succeeded
...
----

. If you plan to store events in ElasticSearch, you must enable the Elastic Cloud on Kubernetes (ECK) Operator. To enable the ECK Operator, create the following manifest in your {OpenShift} environment:
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-eck-operator-certified
  namespace: service-telemetry
spec:
  channel: stable
  installPlanApproval: Automatic
  name: elasticsearch-eck-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
EOF
----

. Verify that the ClusterServiceVersion for Elastic Cloud on Kubernetes `Succeeded`:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc get csv

NAME                                          DISPLAY                        VERSION   REPLACES                                     PHASE
...
elasticsearch-eck-operator-certified.v1.7.1   Elasticsearch (ECK) Operator   1.7.1     elasticsearch-eck-operator-certified.v1.6.0  Succeeded
...
----

. Create the Service Telemetry Operator subscription to manage the {ProjectShort} instances:
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-telemetry-operator
  namespace: service-telemetry
spec:
  channel: stable-1.3
  installPlanApproval: Automatic
  name: service-telemetry-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----

. Validate the Service Telemetry Operator and the dependent operators:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc get csv --namespace service-telemetry

amq7-cert-manager.v1.0.1                      Red Hat Integration - AMQ Certificate Manager   1.0.1                                                          Succeeded
amq7-interconnect-operator.v1.10.1            Red Hat Integration - AMQ Interconnect          1.10.1           amq7-interconnect-operator.v1.2.4             Succeeded
elasticsearch-eck-operator-certified.v1.8.0   Elasticsearch (ECK) Operator                    1.8.0            elasticsearch-eck-operator-certified.v1.7.1   Succeeded
prometheusoperator.0.47.0                     Prometheus Operator                             0.47.0           prometheusoperator.0.37.0                     Succeeded
service-telemetry-operator.v1.3.1632925572    Service Telemetry Operator                      1.3.1632925572                                                 Succeeded
smart-gateway-operator.v3.0.1632925565        Smart Gateway Operator                          3.0.1632925565                                                 Succeeded
----
