[id='configuring-ephemeral-storage_{context}']
= Configuring ephemeral storage

[role="_abstract"]
To configure {ProjectShort} components for ephemeral storage, add `...storage.strategy: ephemeral` to the corresponding parameter. For example, to enable ephemeral storage for the Prometheus back end, set `backends.metrics.prometheus.storage.strategy: ephemeral`. Components that support configuration of ephemeral storage include `alerting.alertmanager`, `backends.metrics.prometheus`, and `backends.events.elasticsearch`. You can add ephemeral storage configuration at installation time or, if you already deployed {ProjectShort}, complete the following steps:

.Procedure

. Log in to {OpenShift}.
. Change to the `openstack-monitoring` namespace:
+
[source,bash]
----
$ oc project openstack-monitoring
----

. Edit the ServiceTelemetry object:
+
[source,bash]
----
$ oc edit stf default
----

. Add the `...storage.strategy: ephemeral` parameter to the `spec` section of the relevant component:
+
[source,yaml]
----
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: stf-default
  namespace: openstack-monitoring
spec:
  alerting:
    enabled: true
    alertmanager:
      storage:
        strategy: ephemeral
  backends:
    metrics:
      prometheus:
        enabled: true
        storage:
          strategy: ephemeral
    events:
      elasticsearch:
        enabled: true
        storage:
          strategy: ephemeral
----

. Save your changes and close the object.
