[id="subscribing-to-the-amq-certificate-manager-operator_{context}"]
= Subscribing to the AMQ Certificate Manager Operator

[role="_abstract"]
You must subscribe to the AMQ Certificate Manager Operator before you deploy the other {ProjectShort} components because the AMQ Certificate Manager Operator runs with cluster scope. The AMQ Certificate Manager Operator is not compatible with the dependency management of Operator Lifecycle Manager when you use it with other namespace-scoped operators.

[NOTE]
The AMQ Certificate Manager deploys to the `openshift-operators` namespace and is then available to all namespaces across the cluster. As a result, on clusters with a large number of namespaces, it can take several minutes for the Operator to be available in the `service-telemetry` namespace.


.Procedure

. Subscribe to the AMQ Certificate Manager Operator by using the `redhat-operators` CatalogSource:

+
[source,bash]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq7-cert-manager-operator
  namespace: openshift-operators
spec:
  channel: 1.x
  installPlanApproval: Automatic
  name: amq7-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----

. Validate your `ClusterServiceVersion`:
+
[source,bash,options="nowrap"]
----
$ oc get --namespace openshift-operators csv

NAME                       DISPLAY                                         VERSION   REPLACES   PHASE
amq7-cert-manager.v1.0.1   Red Hat Integration - AMQ Certificate Manager   1.0.1                Succeeded
----
+
Ensure that amq7-cert-manager.v1.0.1 displays a phase of `Succeeded`.
