[id="creating-a-route-in-ocp_{context}"]
= Creating a route in {OpenShift}

[role="_abstract"]
In {OpenShift}, you can expose applications to the external network through a route. For more information, see https://docs.openshift.com/container-platform/{NextSupportedOpenShiftVersion}/networking/configuring_ingress_cluster_traffic/overview-traffic.html[Configuring ingress cluster traffic].

In {Project} ({ProjectShort}), routes are not exposed by default  to limit the attack surface of {ProjectShort} deployments. To access some services deployed in {ProjectShort}, you must expose the services in {OpenShift} for access.

A common service to expose in {ProjectShort} is Prometheus, as shown in the following example:

.Procedure

. Log in to {OpenShift}.
. Change to the `service-telemetry` namespace:
+
[source,bash]
----
$ oc project service-telemetry
----

. List the available services in the `service-telemetry` project:
+
[source,bash]
----
$ oc get services
----
+
[source,bash,options="nowrap"]
----
NAME                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                         AGE
alertmanager-operated                    ClusterIP   None             <none>        9093/TCP,9094/TCP,9094/UDP                      93m
default-cloud1-ceil-meter-smartgateway   ClusterIP   172.30.114.195   <none>        8081/TCP                                        93m
default-cloud1-coll-meter-smartgateway   ClusterIP   172.30.133.180   <none>        8081/TCP                                        93m
default-interconnect                     ClusterIP   172.30.3.241     <none>        5672/TCP,8672/TCP,55671/TCP,5671/TCP,5673/TCP   93m
ibm-auditlogging-operator-metrics        ClusterIP   172.30.216.249   <none>        8383/TCP,8686/TCP                               11h
prometheus-operated                      ClusterIP   None             <none>        9090/TCP                                        93m
service-telemetry-operator-metrics       ClusterIP   172.30.11.66     <none>        8383/TCP,8686/TCP                               11h
smart-gateway-operator-metrics           ClusterIP   172.30.145.199   <none>        8383/TCP,8686/TCP                               11h
----

. Take note of the port and service name that you want to expose as a route, for example, service `prometheus-operated` and port `9090`.

. Expose the `prometheus-operated` service as an edge route and redirect insecure traffic to the secure endpoint of port `9090`:
+
[source,bash,options="nowrap"]
----
$ oc create route edge metrics-store --service=prometheus-operated --insecure-policy="Redirect" --port=9090
----
+
----
route.route.openshift.io/metrics-store created
----

. To verify and find the exposed external DNS for the route, use the `oc get route` command:
+
[source,bash]
----
$ oc get route metrics-store -ogo-template='{{.spec.host}}'
----
+
----
metrics-store-service-telemetry.apps.infra.watch
----

+
The `prometheus-operated` service is now available at the exposed DNS address, for example, https://metrics-store-service-telemetry.apps.infra.watch
+
[NOTE]
The address of the route must be resolvable and configuration is environment specific.

.Additional resources

* For more information about {OpenShift} networking, see https://docs.openshift.com/container-platform/{SupportedOpenShiftVersion}/networking/understanding-networking.html[Understanding networking]
* For more information about route configuration, see https://docs.openshift.com/container-platform/{SupportedOpenShiftVersion}/networking/routes/route-configuration.html[Route configuration]
* For more information about ingress cluster traffic, see https://docs.openshift.com/container-platform/{SupportedOpenShiftVersion}/networking/configuring_ingress_cluster_traffic/overview-traffic.html[Configuring ingress cluster traffic overview]
