// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_configuring-high-availability.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="configuring-high-availability_{context}"]
= Configuring High Availability

High availability refers to the ability of {Project} to rapidly recover from failures in its component services. While {OpenShift} will restart a failed pod if nodes are available to schedule the workload, this recovery process can take anywhere from several seconds to over a minute, during which time events and metrics are lost. Deploying in a high availability configuration runs multiple copies of {ProjectShort} components, reducing this recovery time to around 2 seconds. In order to protect against failure of an {OpenShiftShort} node, it is recommended that {ProjectShort} be deployed to an {OpenShiftShort} cluster with 3 or more nodes.

[NOTE]
{ProjectShort} is not yet a fully fault tolerant system. Delivery of metrics and events during the recovery period is not guaranteed.

Enabling high availability has the following effects:

- 2 {MessageBus} pods will run instead of the default 1
- 3 ElasticSearch pods will run instead of the default 1
- Recovery time from a lost pod in either of these services is reduced to ~2s

[NOTE]
High availability for the Smart Gateway and Prometheus components of {ProjectShort} is still a work in progress


To configure {ProjectShort} for High Availability, the `highAvailabilityEnabled: true` attribute must be added to the ServiceTelemetry object in {OpenShiftShort}.

This can either be set at installation time, or if you already have {ProjectShort} deployed, you can follow this procedure:

. Use the oc command to edit the servicetelemetry object:
+
----
    oc edit ServiceTelemetry
----

. Add the `highAvailabilityEnabled: true` parameter to the spec section:
+
----
spec:
  eventsEnabled: true
  metricsEnabled: true
  highAvailabilityEnabled: true
----

. Save your changes 
