[id="configuring-the-stf-connection-for-the-overcloud_{context}"]
= Configuring the {ProjectShort} connection for the overcloud

[role="_abstract"]
To configure the {Project} ({ProjectShort}) connection, you must create a file that contains the connection configuration of the {MessageBus} for the overcloud to the {ProjectShort} deployment. Enable the collection of events and storage of the events in {ProjectShort} and deploy the overcloud. The default configuration is for a single cloud instance with the default message bus topics. For configuration of multiple cloud deployments, see xref:configuring-multiple-clouds_assembly-completing-the-stf-configuration[].

.Prerequisites

ifdef::include_when_13[]
* Retrieve the CA certificate from the {MessageBus} deployed by {ProjectShort}. For more information, see xref:getting-ca-certificate-from-stf-for-overcloud-configuration_assembly-completing-the-stf-configuration[].
endif::include_when_13[]
* Retrieve the {MessageBus} route address. For more information, see xref:retrieving-the-qdr-route-address_assembly-completing-the-stf-configuration[].

// The following configuration should match the contents in modules/proc_creating-openstack-environment-file-for-multiple-clouds.adoc. If you have changes to make, please make the same changes to both files.
.Procedure

. Log in to the {OpenStackShort} undercloud as the `stack` user.

. Create a configuration file called `stf-connectors.yaml` in the `/home/stack` directory.

. In the `stf-connectors.yaml` file, configure the `MetricsQdrConnectors` address to connect the {MessageBus} on the overcloud to the {ProjectShort} deployment. The topic addresses for Sensubility, Ceilometer, and collectd are configured here to match the defaults in {ProjectShort}. For more information about customizing topics and cloud configuration, see xref:configuring-multiple-clouds_assembly-completing-the-stf-configuration[].

* Replace the `host` parameter with the value of `HOST/PORT` that you retrieved in xref:retrieving-the-qdr-route-address_assembly-completing-the-stf-configuration[].

ifdef::include_when_13[]
* Replace the `caCertFileContent` parameter with the contents retrieved in xref:getting-ca-certificate-from-stf-for-overcloud-configuration_assembly-completing-the-stf-configuration[].
endif::include_when_13[]
+
.stf-connectors.yaml
[source,yaml,options="nowrap"]
----
resource_registry:
  OS::TripleO::Services::Collectd: /usr/share/openstack-tripleo-heat-templates/deployment/metrics/collectd-container-puppet.yaml    # <1>

parameter_defaults:
    MetricsQdrConnectors:
        - host: stf-default-interconnect-5671-service-telemetry.apps.infra.watch   # <2>
          port: 443
          role: edge
          verifyHostname: false
          sslProfile: sslProfile

    MetricsQdrSSLProfiles:
        - name: sslProfile
ifdef::include_when_13[]
          caCertFileContent: |
            ----BEGIN CERTIFICATE----
            <snip>
            ----END CERTIFICATE----
endif::include_when_13[]

    CeilometerQdrEventsConfig:
        driver: amqp
        topic: cloud1-event   # <3>

    CeilometerQdrMetricsConfig:
        driver: amqp
        topic: cloud1-metering   # <4>

    CollectdAmqpInstances:
        cloud1-notify:        # <5>
            notify: true
            format: JSON
            presettle: false
        cloud1-telemetry:     # <6>
            format: JSON
            presettle: false

ifdef::include_when_16[]
    CollectdSensubilityResultsChannel: sensubility/cloud1-telemetry # <7>
endif::include_when_16[]
----
<1> Directly load the collectd service because you are not including the `collectd-write-qdr.yaml` environment file for multiple cloud deployments.
<2> Replace the `host` parameter with the value of `HOST/PORT` that you retrieved in xref:retrieving-the-qdr-route-address_assembly-completing-the-stf-configuration[].
<3> Define the topic for Ceilometer events. This value is the address format of `anycast/ceilometer/cloud1-event.sample`.
<4> Define the topic for Ceilometer metrics. This value is the address format of `anycast/ceilometer/cloud1-metering.sample`.
<5> Define the topic for collectd events. This value is the format of `collectd/cloud1-notify`.
<6> Define the topic for collectd metrics. This value is the format of `collectd/cloud1-telemetry`.
ifdef::include_when_16[]
<7> Define the topic for collectd-sensubility events. Ensure that this value is the exact string format `sensubility/cloud1-telemetry`
endif::include_when_16[]
