// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_configuring-manifest-overrides.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="configuring-manifest-overrides_{context}"]
= Overriding a managed manifest

Edit the `ServiceTelemetry` object and provide a parameter and manifest. For a list of available manifest override parameters, see xref:manifest-overrides_advanced-features[]. The default `ServiceTelemetry` object is `default`. Use `oc get servicetelemetry` to list the available {ProjectShort} deployments.

[TIP]
The `oc edit` command loads the default system editor. To override the default editor, pass or set the environment variable `EDITOR` to the preferred editor. For example, `EDITOR=nano oc edit servicetelemetry default`.

[discrete]
== Procedure

. Log in to {OpenShift}.
. Change to the `service-telemetry` namespace:
+
[source,bash]
----
oc project service-telemetry
----

. Load the `ServiceTelemetry` object into an editor:
+
[source,bash]
----
oc edit servicetelemetry default
----

. To modify the `ServiceTelemetry` object, provide a manifest override parameter and the contents of the manifest to write to {OpenShiftShort} instead of the defaults provided by {ProjectShort}.
+
NOTE: The trailing pipe (`|`) after entering the manifest override parameter indicates that the value provided is multi-line.

+
[source,yaml,options="nowrap"]
----
$ oc edit stf default

apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  ...
spec:
  alertmanagerConfigManifest: | <1>
    apiVersion: v1
    kind: Secret
    metadata:
      name: 'alertmanager-default'
      namespace: 'service-telemetry'
    type: Opaque
    stringData:
      alertmanager.yaml: |-
        global:
          resolve_timeout: 10m
        route:
          group_by: ['job']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'null'
        receivers:
        - name: 'null' <2>
status:
  ...
----
+
<1> Manifest override parameter is defined in the `spec` of the `ServiceTelemetry` object.
<2> End of the manifest override content.

. Save and close.
