[id="configuring-tls-certificates-duration_{context}"]
= Configuring TLS certificates duration

[role="_abstract"]
To configure the duration of the TLS certificates to use with {Project} ({ProjectShort}), modify the `ServiceTelemetry` object and configure the `certificates` parameter.

.Prerequisites

* You didn't deploy an instance of Service Telemetry Operator already.

NOTE: When you create the `ServiceTelemetry` object, the required certificates and their secrets for {ProjectShort} are also created.
For more information about how to modify the certificates and the secrets, see: xref:assembly-renewing-the-amq-interconnect-certificate_assembly[].
The following procedure is valid for new {ProjectShort} deployments.

.Procedure

. To edit the duration of the TLS certificate, you can set the QDR `caCertDuration`, for example `87600h` for 10 years:
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
$ oc apply -f - <<EOF
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: default
  namespace: service-telemetry
spec:
  transport:
    qdr:
      enabled: true
      certificates:
        caCertDuration: 87600h
EOF
----

.Verification

. Verify that the expiry date for the certificate is correct:
+
[source,bash,options="nowrap"]
----
$ oc get secret  default-interconnect-selfsigned -o jsonpath='{.data.tls\.crt}' | base64 -d  | openssl x509 -in - -text | grep "Not After"
            Not After : Mar  9 21:00:16 2033 GMT
----
