// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_deploying-with-routed-l3-networks.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="deploying-with-routed-l3-networks_{context}"]
= Deploying with routed L3 networks
If your nodes are on a separate network from the default `InternalApi` network that the Controller nodes use, you must make several changes so that {MessageBus} can transport data to the {ProjectShort} server instance. This scenario is typical in a spine-leaf or a DCN topology.

[discrete]
.Procedure

* Add the following configuration example to the `ExtraConfig` section for each Compute node. In this example, `internal_apiN` is the network to which the Compute node `N` is connected. `N` represents a value that is different from the default internal API network name.

[source,yaml]
----
ComputeNExtraConfig:
›   tripleo::profile::base::metrics::collectd::amqp_host: "%{hiera('internal_apiN')}"
›   tripleo::profile::base::metrics::qdr::listener_addr: "%{hiera('internal_apiN')}"
----

[discrete]
.Additional resources

For more information about DCN configuration, see the link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html-single/spine_leaf_networking/[Spine Leaf Networking] guide.
