[id="disabling-openstack-services-used-with-stf_{context}"]
= Disabling {OpenStack} services used with {Project}

[role="_abstract"]
Disable the services used when deploying {OpenStack} ({OpenStackShort}) and connecting it to {Project} ({ProjectShort}).  There is no removal of logs or generated configuration files as part of the disablement of the services.

.Procedure

. Log in to the undercloud host as the `stack` user.

. Source the `stackrc` undercloud credentials file:
+
[source,bash]
----
$ source ~/stackrc
----

. Create the `disable-stf.yaml` environment file:
+
[source,yaml,options="nowrap"]
----
$ cat > ~/disable-stf.yaml <<EOF
---
resource_registry:
  OS::TripleO::Services::CeilometerAgentCentral: OS::Heat::None
  OS::TripleO::Services::CeilometerAgentNotification: OS::Heat::None
  OS::TripleO::Services::CeilometerAgentIpmi: OS::Heat::None
  OS::TripleO::Services::ComputeCeilometerAgent: OS::Heat::None
  OS::TripleO::Services::Redis: OS::Heat::None
  OS::TripleO::Services::Collectd: OS::Heat::None
  OS::TripleO::Services::MetricsQdr: OS::Heat::None
EOF
----

. Remove the following files from your {OpenStackShort} {OpenStackInstaller} deployment:
+
* `ceilometer-write-qdr.yaml`
* `qdr-edge-only.yaml`
* `enable-stf.yaml`
* `stf-connectors.yaml`

. Update the {OpenStackShort} overcloud. Ensure that you use the `disable-stf.yaml` file early in the list of environment files. By adding `disable-stf.yaml` early in the list, other environment files can override the configuration that would disable the service:
+
[source,bash,options="nowrap"]
----
(undercloud)$ openstack overcloud deploy --templates \
-e /home/stack/disable-stf.yaml \
-e [your environment files]
----
