[id="deploying-smart-gateways_{context}"]
= Deploying Smart Gateways

[role="_abstract"]
ifdef::include_when_16[]
You must deploy a Smart Gateway for each of the data collection types for each cloud; one for collectd metrics, one for collectd events, one for Ceilometer metrics, one for Ceilometer events, and one for collectd-sensubility metrics. Configure each of the Smart Gateways to listen on the AMQP address that you define for the corresponding cloud. To define Smart Gateways, configure the `clouds` parameter in the `ServiceTelemetry` manifest.
endif::include_when_16[]
ifdef::include_when_13[]
You must deploy a Smart Gateway for each of the data collection types for each cloud; one for collectd metrics, one for collectd events, one for Ceilometer metrics, and one for Ceilometer events. Configure each of the Smart Gateways to listen on the AMQP address that you define for the corresponding cloud. To define Smart Gateways, configure the `clouds` parameter in the `ServiceTelemetry` manifest.
endif::include_when_13[]

When you deploy {ProjectShort} for the first time, Smart Gateway manifests are created that define the initial Smart Gateways for a single cloud. When you deploy Smart Gateways for multiple cloud support, you deploy multiple Smart Gateways for each of the data collection types that handle the metrics and the events data for each cloud. The initial Smart Gateways are defined in `cloud1` with the following subscription addresses:

|===
| **collector** | **type** | **default subscription address**
| collectd | metrics | collectd/telemetry
| collectd | events | collectd/notify
ifdef::include_when_16[]
| collectd-sensubility | metrics | sensubility/telemetry
endif::include_when_16[]
| Ceilometer | metrics | anycast/ceilometer/metering.sample
| Ceilometer | events | anycast/ceilometer/event.sample
|===

.Prerequisites

* You have determined your cloud naming scheme. For more information about determining your naming scheme, see xref:planning-amqp-address-prefixes_assembly-completing-the-stf-configuration[].

* You have created your list of clouds objects. For more information about creating the content for the `clouds` parameter, see xref:clouds_assembly-installing-the-core-components-of-stf[].

.Procedure

. Log in to {OpenShift}.
. Change to the `openstack-monitoring` namespace:
+
[source,bash]
----
$ oc project openstack-monitoring
----

. Edit the `default` ServiceTelemetry object and add a `clouds` parameter with your configuration:
+
[WARNING]
====
Long cloud names might exceed the maximum pod name of 63 characters. Ensure that the combination of the `ServiceTelemetry` name `default` and the `clouds.name` does not exceed 19 characters. Cloud names cannot contain any special characters, such as `-`. Limit cloud names to alphanumeric (a-z, 0-9).

Topic addresses have no character limitation and can be different from the `clouds.name` value.
====
+
[source,bash]
----
$ oc edit stf default
----
+
[source,yaml,options="nowrap"]
----
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  ...
spec:
  ...
  clouds:
  - name: cloud1
    events:
      collectors:
      - collectorType: collectd
        subscriptionAddress: collectd/cloud1-notify
      - collectorType: ceilometer
        subscriptionAddress: anycast/ceilometer/cloud1-event.sample
    metrics:
      collectors:
      - collectorType: collectd
        subscriptionAddress: collectd/cloud1-telemetry
ifdef::include_when_16[]
      - collectorType: sensubility
        subscriptionAddress: sensubility/cloud1-telemetry
endif::include_when_16[]
      - collectorType: ceilometer
        subscriptionAddress: anycast/ceilometer/cloud1-metering.sample
  - name: cloud2
    events:
      ...
----

. Save the ServiceTelemetry object.

. Verify that each Smart Gateway is running. This can take several minutes depending on the number of Smart Gateways:
+
[source,bash,options="nowrap"]
----
$ oc get po -l app=smart-gateway
NAME                                                      READY   STATUS    RESTARTS   AGE
default-cloud1-ceil-event-smartgateway-6cfb65478c-g5q82   2/2     Running   0          13h
default-cloud1-ceil-meter-smartgateway-58f885c76d-xmxwn   2/2     Running   0          13h
default-cloud1-coll-event-smartgateway-58fbbd4485-rl9bd   2/2     Running   0          13h
default-cloud1-coll-meter-smartgateway-7c6fc495c4-jn728   2/2     Running   0          13h
ifdef::include_when_16[default-cloud1-sens-meter-smartgateway-8h4tc445a2-mm683   2/2     Running   0          13h]
----
