// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_subscribing-to-the-service-telemetry-operator.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="subscribing-to-the-service-telemetry-operator_{context}"]
= Subscribing to the Service Telemetry Operator

[role="_abstract"]
You must subscribe to the Service Telemetry Operator, which manages the {ProjectShort} instances.

.Procedure

. To create the Service Telemetry Operator subscription, enter the `oc create -f` command:
+
ifeval::["{build}" == "upstream"]
[source,bash]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-telemetry-operator
  namespace: service-telemetry
spec:
  channel: stable-1.3
  installPlanApproval: Automatic
  name: service-telemetry-operator
  source: infrawatch-operators
  sourceNamespace: openshift-marketplace
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
[source,bash]
----
$ oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-telemetry-operator
  namespace: service-telemetry
spec:
  channel: stable-1.3
  installPlanApproval: Automatic
  name: service-telemetry-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----
endif::[]


. To validate the Service Telemetry Operator and the dependent operators, enter the following command:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc get csv --namespace service-telemetry

NAME                                         DISPLAY                                         VERSION          REPLACES                            PHASE
amq7-cert-manager.v1.0.0                     Red Hat Integration - AMQ Certificate Manager   1.0.0                                                Succeeded
amq7-interconnect-operator.v1.2.3            Red Hat Integration - AMQ Interconnect          1.2.3            amq7-interconnect-operator.v1.2.2   Succeeded
elastic-cloud-eck.v1.6.0                     Elasticsearch (ECK) Operator                    1.6.0            elastic-cloud-eck.v1.5.0            Succeeded
prometheusoperator.0.47.0                    Prometheus Operator                             0.47.0           prometheusoperator.0.37.0           Succeeded
service-telemetry-operator.v1.3.1622734200   Service Telemetry Operator                      1.3.1622734200                                       Succeeded
smart-gateway-operator.v3.0.1622734308       Smart Gateway Operator                          3.0.1622734308                                       Succeeded
----
