// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_configuring-red-hat-openstack-platform-overcloud-for-stf.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="configuring-red-hat-openstack-platform-overcloud-for-stf_{context}"]
= Configuring {OpenStack} overcloud for {ProjectShort}

To configure the {OpenStack} overcloud, you must configure collectd and {MessageBus}:

. Create a file and name it `stf-connectors.yaml`.
. Save the file in the `/home/stack` directory.
. Retrieve the QDR route address for the `MetricsQdrConnectors` host parameter. For more information, see <<retrieving-the-qdr-route-address>>.
. In the `stf-connectors.yaml` file, configure the `MetricsQdrConnectors` address to connect the {MessageBus} bus on the overcloud to the {ProjectShort} deployment. The following sample is from the `stf-connectors.yaml` environment file:
+
----
parameter_defaults:
    MetricsQdrConnectors:
    - host: stf-default-interconnect-5671-service-telemetry.apps.infra.watch
      port: 443
      role: edge
      sslProfile: sslProfile
      verifyHostname: false
----

. Add the `stf-connectors.yaml` environment file to a {OpenStack}{OpenStackInstaller} deployment to configure and setup collectd and {MessageBus}. Add the `enable-stf.yaml` file to the deployment to ensure that the environment is being used during the overcloud deployment. Add the `ceilometer-write-qdr.yaml` file to the deployment to ensure that Ceilometer telemetry is sent to {ProjectShort}:
+
----
openstack overcloud deploy <other arguments>
--templates /usr/share/openstack-tripleo-heat-templates \
  --environment-file <...other-environment-files...> \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/ceilometer-write-qdr.yaml \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/enable-stf.yaml \
  --environment-file /home/stack/stf-connectors.yaml
----

[[retrieving-the-qdr-route-address]]
== Retrieving the QDR route address

When you configure the {OpenStack} overcloud for {ProjectShort}, you must provide the QDR route address for the `MetricsQdrConnectors` host parameter.

. Run the `oc get routes` command:
+
----
oc get routes
NAME                             HOST/PORT                                                                                        PATH   SERVICES                   PORT    TERMINATION        WILDCARD
stf-default-interconnect-55671   stf-default-interconnect-55671-service-telemetry.apps.stfcloudops1.lab.upshift.rdu2.redhat.com          stf-default-interconnect   55671   passthrough/None   None
stf-default-interconnect-5671    stf-default-interconnect-5671-service-telemetry.apps.stfcloudops1.lab.upshift.rdu2.redhat.com           stf-default-interconnect   5671    passthrough/None   None
stf-default-interconnect-8672    stf-default-interconnect-8672-service-telemetry.apps.stfcloudops1.lab.upshift.rdu2.redhat.com           stf-default-interconnect   8672    edge/Redirect      None
----

. Use the value in `HOST/PORT` for the `stf-default-interconnect-5671` route for the `MetricsQdrConnectors` host value, for example:
+
----
        MetricsQdrConnectors:
            - host: stf-default-interconnect-5671-service-telemetry.apps.stfcloudops1.lab.upshift.rdu2.redhat.com
              port: 443
              role: edge
              verifyHostname: false
              sslProfile: sslProfile
----
