
[id="editing-the-metrics-retention-time-period-in-service-telemetry-framework_{context}"]
= Editing the metrics retention time period in Service Telemetry Framework

[role="_abstract"]
You can adjust {Project} ({ProjectShort}) for additional metrics retention time.

.Procedure

. Log in to {OpenShift}.

. Change to the service-telemetry namespace:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc project service-telemetry
----

. Edit the ServiceTelemetry object:
+
[source,bash,options="nowrap",role="white-space-pre"]
----
$ oc edit stf default
----

. Add `retention: 7d`  to the storage section of backends.metrics.prometheus.storage to increase the retention period to seven days:
+
[NOTE]
If you set a long retention period, retrieving data from heavily populated Prometheus systems can result in queries returning results slowly.
+
[source,yaml,options="nowrap",role="white-space-pre"]
----
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: stf-default
  namespace: service-telemetry
spec:
  ...
  backends:
    metrics:
      prometheus:
        enabled: true
        storage:
          strategy: persistent
          retention: 7d
    ...
----

. Save your changes and close the object.
. Wait for prometheus to restart with the new settings.
+
[source,bash]
----
$ oc get po -l app.kubernetes.io/name=prometheus -w
----
. Verify the new retention setting be checking the command line arguments used in the pod.
+
[source,bash]
----
$ oc describe po prometheus-default-0 | grep retention.time
      --storage.tsdb.retention.time=24h
----

.Additional resources

* For more information about the metrics retention time, see xref:metrics-retention-time-period_assembly-advanced-features[].
