// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_setting-up-the-dashboard-to-host-grafana.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="setting-up-grafana-to-host-the-dashboard_{context}"]
= Setting up Grafana to host the dashboard

Grafana is not included in the default {Project} ({ProjectShort}) deployment so you must deploy the Grafana Operator from OperatorHub.io. Using the Service Telemetry Operator to deploy Grafana results in a Grafana instance and the  configuration of the default data sources for the local {ProjectShort} deployment.

[discrete]
.Prerequisites

Enable OperatorHub.io catalog source for the Grafana Operator. For more information, see xref:enabling-the-operatorhubio-community-catalog-source[].

.Procedure

. Log in to {OpenShift}.
. Change to the `service-telemetry` namespace:
+
[source,bash]
----
oc project service-telemetry
----

. Deploy the Grafana operator:
+
[source,bash]
----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: service-telemetry
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: grafana-operator
  source: operatorhubio-operators
  sourceNamespace: openshift-marketplace
EOF
----

. To verify that the operator launched successfully, run the `oc get csv` command. If the value of the PHASE column is Succeeded, the operator launched successfully:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc get csv
----
+
[source,bash,options="nowrap"]
----
NAME                                DISPLAY                                         VERSION   REPLACES                            PHASE
grafana-operator.v3.2.0             Grafana Operator                                3.2.0                                         Succeeded
...
----

. To launch a Grafana instance, create or modify the `ServiceTelemetry` object. Set `graphingEnabled` to `true`.
+
[source,bash]
----
$ oc edit ServiceTelemetry stf-default
----
+
[source,yaml]
----
apiVersion: infra.watch/v1alpha1
kind: ServiceTelemetry
...
spec:
  graphingEnabled: true
  ...
----

. Verify that the Grafana instance deployed:
+
[source,bash]
----
$ oc get pod -l app=grafana
----
+
----
NAME                                  READY   STATUS    RESTARTS   AGE
grafana-deployment-7fc7848b56-sbkhv   1/1     Running   0          1m
----

.Additional resources

* For more information about enabling the OperatorHub.io catalog source, see xref:enabling-the-operatorhubio-community-catalog-source[].


[id="importing-dashboards_{context}"]
= Importing dashboards

Dashboards can be imported and managed by the Grafana Operator by creating `GrafanaDashboard` objects. Example dashboards are provided at https://github.com/infrawatch/dashboards.

.Procedure

. Import a dashboard:
+
[source,bash,options="nowrap"]
----
$ oc apply -f https://raw.githubusercontent.com/infrawatch/dashboards/master/deploy/rhos-dashboard.yaml
----
+
----
grafanadashboard.integreatly.org/rhos-dashboard created
----

. Verify that the resources installed correctly:
+
[source,bash]
----
$ oc get grafanadashboards
----
+
----
NAME             AGE
rhos-dashboard   7d21h
----
+
[source,bash]
----
$ oc get grafanadatasources
----
+
----
NAME                        AGE
stf-default-ds-prometheus   20h
----

. Expose the grafana service as a route:
+
[source,bash,options="nowrap"]
----
oc create route edge dashboards --service=grafana-service --insecure-policy="Redirect" --port=3000
----

. Navigate to https://<grafana-route-address> in a web browser. Use the `oc get routes` command to retrieve the Grafana route address:
+
[source,bash]
----
oc get route dashboards
----
+
[source,bash,options="nowrap"]
----
NAME         HOST/PORT                                                                    PATH   SERVICES          PORT   TERMINATION     WILDCARD
dashboards   dashboards-service-telemetry.apps.stfcloudops1.lab.upshift.rdu2.redhat.com          grafana-service   3000   edge/Redirect   None
----

. To view the dashboard, click *Dashboards* and *Manage*.


[id="viewing-and-editing-queries"]
= Viewing and editing queries

.Procedure

. Log in to {OpenShift}. To view and edit queries, log in as the `admin` user.
. Change to the `service-telemetry` namespace:
+
[source,bash]
----
oc project service-telemetry
----

. To retrieve the default username and password, describe the Grafana object using `oc describe`:
+
[source,bash]
----
oc describe grafana service-telemetry-grafana
----
