// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_deploying-stf-to-the-openshift-environment.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="deploying-stf-to-the-openshift-environment_{context}"]
= Deploying {ProjectShort} to the {OpenShiftShort} environment

You can deploy {ProjectShort} to the {OpenShiftShort} environment in one of two ways:

* Deploy {ProjectShort} and store events with ElasticSearch. For more information, see <<deploying-stf-to-the-openshift-environment-with-elasticsearch>>.
* Deploy {ProjectShort} without ElasticSearch and disable events support. For more information, see <<deploying-stf-to-the-openshift-environment-without-elasticsearch>>.

[id="deploying-stf-to-the-openshift-environment-with-elasticsearch"]
== Deploying {ProjectShort} to the {OpenShiftShort} environment with ElasticSearch

Complete the following tasks:

. Create a namespace. For more information, see <<creating-a-namespace>>.
. Create an OperatorGroup. For more information, see <<creating-an-operatorgroup>>.
. Enable the OperatorHub.io Community Catalog Source. For more information, see <<enabling-the-operatorhubio-community-catalog-source>>.
ifeval::["{build}" == "upstream"]
. Enable the InfraWatch Operator Source. For more information, see <<enabling-the-infrawatch-operator-source>>.
endif::[]
ifeval::["{build}" == "downstream"]
. Enable the Red Hat STF Operator Source. For more information, see <<enabling-the-infrawatch-operator-source>>.
endif::[]
. Subscribe to the AMQ Certificate Manager Operator. For more information, see <<subscribing-to-the-amq-certificate-manager-operator>>.
. Subscribe to the Elastic Cloud on Kubernetes Operator. For more information, see <<subscribing-to-elastic-cloud-on-kubernetes-operator>>.
. Subscribe to the Service Telemetry Operator. For more information, see <<subscribing-to-the-service-telemetry-operator>>.
. Create a ServiceTelemetry object in {OpenShiftShort}. For more information, see <<creating-a-servicetelemetry-object-in-openshift>>.

[id="deploying-stf-to-the-openshift-environment-without-elasticsearch"]
== Deploying {ProjectShort} to the {OpenShiftShort} environment without ElasticSearch

Complete the following tasks:

. Create a namespace. For more information, see <<creating-a-namespace>>.
. Create an OperatorGroup. For more information, see <<creating-an-operatorgroup>>.
ifeval::["{build}" == "upstream"]
. Enable the InfraWatch Operator Source. For more information, see <<enabling-the-infrawatch-operator-source>>.
endif::[]
ifeval::["{build}" == "downstream"]
. Enable the Red Hat STF Operator Source. For more information, see <<enabling-the-infrawatch-operator-source>>.
endif::[]
. Subscribe to the AMQ Certificate Manager Operator. For more information, see <<subscribing-to-the-amq-certificate-manager-operator>>.
. Subscribe to the Service Telemetry Operator. For more information, see <<subscribing-to-the-service-telemetry-operator>>.
. Create a ServiceTelemetry object in {OpenShiftShort}. For more information, see <<creating-a-servicetelemetry-object-in-openshift>>.


[id="creating-a-namespace"]
== Creating a namespace

Create a namespace to hold the {ProjectShort} components. The `service-telemetry` namespace is used throughout the documentation:

----
oc new-project service-telemetry
----

[id="creating-an-operatorgroup"]
== Creating an OperatorGroup

Create an OperatorGroup in the namespace so that you can schedule the Operator pods:

----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: service-telemetry-operator-group
  namespace: service-telemetry
spec:
  targetNamespaces:
  - service-telemetry
EOF
----

[discrete]
== Additional resources

For more information, see https://docs.openshift.com/container-platform/4.3/operators/understanding_olm/olm-understanding-operatorgroups.html[OperatorGroups].

[id="enabling-the-operatorhubio-community-catalog-source"]
== Enabling the OperatorHub.io Community Catalog Source

Before you install ElasticSearch, you must have access to the resources on the OperatorHub.io Community Catalog Source:

[source,bash]
----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/operator-framework/upstream-community-operators:latest
  displayName: OperatorHub.io Operators
  publisher: OperatorHub.io
EOF
----

[id="enabling-the-infrawatch-operator-source"]
ifeval::["{build}" == "upstream"]
== Enabling InfraWatch Operator Source
endif::[]
ifeval::["{build}" == "downstream"]
== Enabling Red Hat STF Operator Source
endif::[]

Before you deploy {ProjectShort} on {OpenShift}, you must enable the operator source.

[discrete]
=== Procedure

. Install an OperatorSource that contains the Service Telemetry Operator and the Smart Gateway Operator:
+

[source,bash]
ifeval::["{build}" == "upstream"]
----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  labels:
    opsrc-provider: infrawatch
  name: infrawatch-operators
  namespace: openshift-marketplace
spec:
  authorizationToken: {}
  displayName: InfraWatch Operators
  endpoint: https://quay.io/cnr
  publisher: InfraWatch
  registryNamespace: infrawatch
  type: appregistry
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  labels:
    opsrc-provider: redhat-operators-stf
  name: redhat-operators-stf
  namespace: openshift-marketplace
spec:
  authorizationToken: {}
  displayName: Red Hat STF Operators
  endpoint: https://quay.io/cnr
  publisher: Red Hat
  registryNamespace: redhat-operators-stf
  type: appregistry
EOF
----
endif::[]

. To validate the creation of your OperatorSource, run the `oc get operatorsources` command. A successful import results in the `MESSAGE` field returning a result of `The object has been successfully reconciled`.
+
[options="nowrap", subs="+quotes"]
ifeval::["{build}" == "upstream"]
----
$ oc get -nopenshift-marketplace operatorsource infrawatch-operators

NAME                   TYPE          ENDPOINT              REGISTRY     DISPLAYNAME            PUBLISHER    STATUS      MESSAGE
infrawatch-operators   appregistry   https://quay.io/cnr   infrawatch   InfraWatch Operators   InfraWatch   Succeeded   The object has been successfully reconciled
----
endif::[]
ifeval::["{build}" == "downstream"]
----
$ oc get -nopenshift-marketplace operatorsource redhat-operators-stf

NAME                   TYPE          ENDPOINT              REGISTRY               DISPLAYNAME             PUBLISHER   STATUS      MESSAGE
redhat-operators-stf   appregistry   https://quay.io/cnr   redhat-operators-stf   Red Hat STF Operators   Red Hat     Succeeded   The object has been successfully reconciled
----
endif::[]

. To validate that the Operators are available from the catalog, run the `oc get packagemanifest` command:
+
[options="nowrap", subs="+quotes"]
ifeval::["{build}" == "upstream"]
----
$ oc get packagemanifests | grep InfraWatch

servicetelemetry-operator                    InfraWatch Operators       7m20s
smartgateway-operator                        InfraWatch Operators       7m20s
----
endif::[]
ifeval::["{build}" == "downstream"]
----
$ oc get packagemanifests | grep "Red Hat STF"

smartgateway-operator                        Red Hat STF Operators      2m50s
servicetelemetry-operator                    Red Hat STF Operators      2m50s
----
endif::[]

[id="subscribing-to-the-amq-certificate-manager-operator"]
== Subscribing to the AMQ Certificate Manager Operator

You must subscribe to the AMQ Certificate Manager Operator before you deploy the other {ProjectShort} components because the AMQ Certificate Manager Operator runs globally-scoped and is not compatible with the dependency management of Operator Lifecycle Manager when used with other namespace-scoped operators.

[discrete]
=== Procedure

. Subscribe to the AMQ Certificate Manager Operator, create the subscription, and validate the AMQ7 Certificate Manager:
+
[NOTE]
The AMQ Certificate Manager is installed globally for all namespaces, so the `namespace` value provided is `openshift-operators`. You might not see your `amq7-cert-manager.v1.0.0` ClusterServiceVersion in the `service-telemetry` namespace for a few minutes until the processing executes against the namespace.

+
[source,bash]
----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq7-cert-manager
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: amq7-cert-manager
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amq7-cert-manager.v1.0.0
EOF
----

. To validate your `ClusterServiceVersion`, run the `oc get csv` command. Ensure that amq7-cert-manager.v1.0.0 has a phase `Succeeded`.
+
[options="nowrap", subs="+quotes"]
----
$ oc get --namespace openshift-operators csv

NAME                       DISPLAY                                         VERSION   REPLACES   PHASE
amq7-cert-manager.v1.0.0   Red Hat Integration - AMQ Certificate Manager   1.0.0                Succeeded
----

[id="subscribing-to-elastic-cloud-on-kubernetes-operator"]
== Subscribing to the Elastic Cloud on Kubernetes Operator

Before you install the Service Telemetry Operator and if you plan to store events in ElasticSearch, you must enable the Elastic Cloud Kubernetes Operator.

[discrete]
=== Procedure

. Apply the following manifest to your {OpenShiftShort} environment to enable the Elastic Cloud on Kubernetes Operator:
+
[source,bash]
----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elastic-cloud-eck
  namespace: service-telemetry
spec:
  channel: stable
  installPlanApproval: Automatic
  name: elastic-cloud-eck
  source: operatorhubio-operators
  sourceNamespace: openshift-marketplace
  startingCSV: elastic-cloud-eck.v1.1.0
EOF
----

. To verify that the `ClusterServiceVersion` for ElasticSearch Cloud on Kubernetes `succeeded`, run the `oc get csv` command:
+
[options="nowrap", subs="+quotes"]
----
$ oc get csv

NAME                       DISPLAY                                         VERSION   REPLACES                   PHASE
elastic-cloud-eck.v1.1.0   Elastic Cloud on Kubernetes                     1.1.0     elastic-cloud-eck.v1.0.1   Succeeded
----

[id="subscribing-to-the-service-telemetry-operator"]
== Subscribing to the Service Telemetry Operator

To instantiate an {ProjectShort} instance, create the `ServiceTelemetry` object to allow the Service Telemetry Operator to create the environment.

[discrete]
=== Procedure

. To create the Service Telemetry Operator subscription, run the `oc apply -f` command:
+
[source,bash]
ifeval::["{build}" == "upstream"]
----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicetelemetry-operator
  namespace: service-telemetry
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicetelemetry-operator
  source: infrawatch-operators
  sourceNamespace: openshift-marketplace
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicetelemetry-operator
  namespace: service-telemetry
spec:
  channel: stable
  installPlanApproval: Automatic
  name: servicetelemetry-operator
  source: redhat-operators-stf
  sourceNamespace: openshift-marketplace
EOF
----
endif::[]


. To validate the Service Telemetry Operator and the dependent operators, run the following command:
+
[options="nowrap", subs="+quotes"]
----
$ oc get csv --namespace service-telemetry
NAME                                DISPLAY                                         VERSION   REPLACES                            PHASE
amq7-cert-manager.v1.0.0            Red Hat Integration - AMQ Certificate Manager   1.0.0                                         Succeeded
amq7-interconnect-operator.v1.2.0   Red Hat Integration - AMQ Interconnect          1.2.0                                         Succeeded
elastic-cloud-eck.v1.1.0            Elastic Cloud on Kubernetes                     1.1.0     elastic-cloud-eck.v1.0.1            Succeeded
prometheusoperator.0.37.0           Prometheus Operator                             0.37.0    prometheusoperator.0.32.0           Succeeded
service-telemetry-operator.v1.0.2   Service Telemetry Operator                      1.0.2     service-telemetry-operator.v1.0.1   Succeeded
smart-gateway-operator.v1.0.1       Smart Gateway Operator                          1.0.1     smart-gateway-operator.v1.0.0       Succeeded
----
