// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_setting-up-the-dashboard-to-host-grafana.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="setting-up-grafana-to-host-the-dashboard_{context}"]
= Setting up Grafana to host the dashboard

[role="_abstract"]
Grafana is not included in the default {Project} ({ProjectShort}) deployment so you must deploy the Grafana Operator from OperatorHub.io. Using the Service Telemetry Operator to deploy Grafana results in a Grafana instance and the  configuration of the default data sources for the local {ProjectShort} deployment.

.Prerequisites

Enable OperatorHub.io catalog source for the Grafana Operator. For more information, see xref:enabling-the-operatorhub-io-community-catalog-source_assembly-installing-the-core-components-of-stf[].

.Procedure

. Log in to {OpenShift}.
. Change to the `service-telemetry` namespace:
+
[source,bash]
----
$ oc project service-telemetry
----

. Deploy the Grafana operator:
+
[source,yaml]
----
$ oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: service-telemetry
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: grafana-operator
  source: operatorhubio-operators
  sourceNamespace: openshift-marketplace
EOF
----

. To verify that the operator launched successfully, run the `oc get csv` command. If the value of the PHASE column is `Succeeded`, the operator launched successfully:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc get csv

NAME                                DISPLAY                                         VERSION   REPLACES                            PHASE
grafana-operator.v3.2.0             Grafana Operator                                3.2.0                                         Succeeded
...
----

. To launch a Grafana instance, create or modify the `ServiceTelemetry` object. Set `graphing.enabled` and `graphing.grafana.ingressEnabled` to `true`.
+
[source,bash]
----
$ oc edit stf default

apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
...
spec:
  ...
  graphing:
    enabled: true
    grafana:
      ingressEnabled: true
----

. Verify that the Grafana instance deployed:
+
[source,bash]
----
$ oc get pod -l app=grafana

NAME                                  READY   STATUS    RESTARTS   AGE
grafana-deployment-7fc7848b56-sbkhv   1/1     Running   0          1m
----

. Verify that the Grafana data sources installed correctly:
+
[source,bash]
----
$ oc get grafanadatasources

NAME                    AGE
default-datasources     20h
----

. Verify the Grafana route exists:
+
[source,bash,options="nowrap"]
----
$ oc get route grafana-route

NAME            HOST/PORT                                          PATH   SERVICES          PORT   TERMINATION   WILDCARD
grafana-route   grafana-route-service-telemetry.apps.infra.watch          grafana-service   3000   edge          None
----

[id="importing-dashboards_{context}"]
= Importing dashboards

The Grafana Operator can import and manage dashboards by creating `GrafanaDashboard` objects. You can view example dashboards at https://github.com/infrawatch/dashboards.

.Procedure

. Import the infrastructure dashboard:
+
[source,bash,options="nowrap"]
----
$ oc apply -f https://raw.githubusercontent.com/infrawatch/dashboards/master/deploy/rhos-dashboard.yaml

grafanadashboard.integreatly.org/rhos-dashboard created
----
. Import the cloud dashboard:
+
[source,bash,options="nowrap"]
----
$ oc apply -f https://raw.githubusercontent.com/infrawatch/dashboards/master/deploy/rhos-cloud-dashboard.yaml

grafanadashboard.integreatly.org/rhos-cloud-dashboard created
----
[WARNING]
====
Some panels in the cloud dashboard require that you set the collectd `virt` plugin parameter `hostname_format` to `name uuid hostname` in the stf-connectors.yaml. If you do not configure this parameter, affected dashboards remain empty.
[source,yaml]
----
parameter_defaults:
    ExtraConfig:
        collectd::plugin::virt::hostname_format: name uuid hostname
----
====

. Verify that the dashboards are available:
+
[source,bash]
----
$ oc get grafanadashboards

NAME                   AGE
rhos-dashboard         7d21h
rhos-cloud-dashboard   7d21h
----

. Retrieve the Grafana route address:
+
[source,bash,options="nowrap"]
----
$ oc get route grafana-route -ojsonpath='{.spec.host}' 

grafana-route-service-telemetry.apps.infra.watch
----

. Navigate to https://<GRAFANA-ROUTE-ADDRESS> in a web browser. Replace <GRAFANA-ROUTE-ADDRESS> with the value that you retrieved in the previous step.

. To view the dashboard, click *Dashboards* and *Manage*.


[id="proc-retrieving-and-setting-grafana-credentials"]
= Retrieving and setting Grafana login credentials

.Procedure

. Log in to {OpenShift}.
. Change to the `service-telemetry` namespace:
+
[source,bash]
----
$ oc project service-telemetry
----
. To retrieve the default username and password, describe the Grafana object:
+
[source,bash]
----
$ oc describe grafana default
----

. To modify the default values of the Grafana administrator username and password through the ServiceTelemetry object, use the `graphing.grafana.adminUser` and `graphing.grafana.adminPassword` parameters.
