:_content-type: PROCEDURE

[id="configuring-the-stf-connection-for-director-operator-for-the-overcloud_{context}"]
= Configuring the STF connection for director Operator for the overcloud

Edit the `heat-env-config-deploy` ConfigMap to create a connection from {OpenStack} ({OpenStackShort}) to {Project}.

.Procedure

. Log in to the {OpenShift} environment where {OpenStackShort} director Operator is deployed and change to the project that hosts your {OpenStackShort} deployment:
+
[source,bash]
----
$ oc project openstack
----

. Open the `heat-env-config-deploy` ConfigMap for editing:
+
[source,bash,options="nowrap",subs="verbatim"]
----
$ oc edit configmap heat-env-config-deploy
----

. Add your `stf-connectors.yaml` configuration to the `heat-env-config-deploy` ConfigMap, appropriate to your environment, save your edits and close the file:
+
.stf-connectors.yaml
[source,yaml,options="nowrap"]
----
apiVersion: v1
data:
  [...]
  stf-connectors.yaml: |
    resource_registry:
      OS::TripleO::Services::Collectd: /usr/share/openstack-tripleo-heat-templates/deployment/metrics/collectd-container-puppet.yaml

    parameter_defaults:
        MetricsQdrConnectors:
            - host: default-interconnect-5671-service-telemetry.apps.ostest.test.metalkube.org
              port: 443
              role: edge
              verifyHostname: false
              sslProfile: sslProfile
              saslUsername: guest@default-interconnect
              saslPassword: <password_from_stf>

        MetricsQdrSSLProfiles:
            - name: sslProfile

        CeilometerQdrMetricsConfig:
            driver: amqp
            topic: cloud1-metering

        CollectdAmqpInstances:
            cloud1-telemetry:
                format: JSON
                presettle: false

        CollectdSensubilityResultsChannel: sensubility/cloud1-telemetry
----

* The `resource_registry` configuration directly loads the collectd service because you do not include the `collectd-write-qdr.yaml` environment file for multiple cloud deployments.
* Replace the `host` sub-parameter of `MetricsQdrConnectors` with the value that you retrieved in xref:retrieving-the-qdr-route-address_assembly-completing-the-stf-configuration[].
* Replace the `<password_from_stf>` portion of the `saslPassword` sub-parameter of `MetricsQdrConnectors` with the value you retrieved in xref:retrieving-the-qdr-password_assembly-completing-the-stf-configuration[].
ifdef::include_when_13,include_when_17[]
* Replace the `caCertFileContent` parameter with the contents retrieved in xref:getting-ca-certificate-from-stf-for-overcloud-configuration_assembly-completing-the-stf-configuration[].
endif::include_when_13,include_when_17[]
* Set `topic` value of `CeilometerQdrMetricsConfig.topic` to define the topic for Ceilometer metrics. The value is a unique topic identifier for the cloud such as `cloud1-metering`.
* Set `CollectdAmqpInstances` sub-parameter to define the topic for collectd metrics. The section name is a unique topic identifier for the cloud such as `cloud1-telemetry`.
ifndef::include_when_13[]
* Set `CollectdSensubilityResultsChannel` to define the topic for collectd-sensubility events. The value is a unique topic identifier for the cloud such as `sensubility/cloud1-telemetry`.
endif::[]

[role="_additional-resources"]
.Additional resources
* For more information about the `stf-connectors.yaml` environment file, see xref:configuring-the-stf-connection-for-the-overcloud_assembly-completing-the-stf-configuration[].

* For more information about adding heat templates to a {OpenStackShort} director Operator deployment, see link:{defaultURL}/rhosp_director_operator_for_openshift_container_platform/assembly_adding-heat-templates-and-environment-files-with-the-director-operator_rhosp-director-operator#doc-wrapper[Adding heat templates and environment files with the director Operator]
