[id="deploying-the-overcloud_{context}"]
= Deploying the overcloud

[role="_abstract"]
Deploy or update the overcloud with the required environment files so that data is collected and transmitted to {Project} ({ProjectShort}).

.Procedure

. Log in to the undercloud host as the `stack` user.

. Source the `stackrc` undercloud credentials file:
+
[source,bash]
----
$ source ~/stackrc
----

. Add your data collection and {MessageBus} environment files to the stack with your other environment files and deploy the overcloud:
+
[source,bash]
----
(undercloud)$ openstack overcloud deploy --templates \
 -e [your environment files] \
 -e /usr/share/openstack-tripleo-heat-templates/environments/metrics/ceilometer-write-qdr.yaml \
 -e /usr/share/openstack-tripleo-heat-templates/environments/metrics/qdr-edge-only.yaml \
 -e /home/stack/enable-stf.yaml \
 -e /home/stack/stf-connectors.yaml
----

* Include the `ceilometer-write-qdr.yaml` file to ensure that Ceilometer telemetry is sent to {ProjectShort}.
* Include the `qdr-edge-only.yaml` file to ensure that the message bus is enabled and connected to {ProjectShort} message bus routers.
* Include the `enable-stf.yaml` environment file to ensure that the defaults are configured correctly.
* Include the `stf-connectors.yaml` environment file to define the connection to {ProjectShort}.
