////
Base the file name and the ID on the module title. For example:
* file name: proc_removing-the-service-telemetry-framework-v1-4-operators.adoc
* ID: [id="proc_removing-the-service-telemetry-framework-v1-4-operators_{context}"]
* Title: = Removing the Service Telemetry Framework v1.4 Operators
////
:_content-type: PROCEDURE

[id="removing-the-service-telemetry-framework-v1-4-operators_{context}"]
= Removing the Service Telemetry Framework v1.4 Operators

Remove the Service Telemetry Framework (STF) v1.4 Operators and the AMQ Certificate Manager Operator from the Red Hat OpenShift Container Platform v4.8.

.Procedure

. Remove the Service Telemetry Operator
. Remove the Smart Gateway Operator
. Remove the AMQ Certificate Manager Operator
. Remove the Grafana Operator

[role="_additional-resources"]
.Additional resources

For more information about removing Operators from the Red Hat OpenShift Container Platform, see link:https://docs.openshift.com/container-platform/4.8///operators/admin/olm-deleting-operators-from-cluster.html[Deleting Operators from a cluster]
