[id="retrieving-the-qdr-password_{context}"]
= Retrieving the {MessageBus} password

[role="_abstract"]
When you configure the {OpenStack} ({OpenStackShort}) overcloud for {Project} ({ProjectShort}), you must provide the {MessageBus} password in the {ProjectShort} connection file.

You can disable basic authentication on the {MessageBus} connection by setting the value of the `transports.qdr.auth` parameter of the ServiceTelemetry spec to `none`. The `transports.qdr.auth` parameter is absent in versions of {ProjectShort} before 1.5.3, so the default behavior is that basic authentication is disabled. In a new install of {ProjectShort} 1.5.3 or later, the default value of  `transports.qdr.auth` is `basic`, but if you upgraded to {ProjectShort} 1.5.3, the default value of `transports.qdr.auth` is `none`.

.Procedure

. Log in to your {OpenShift} environment where {ProjectShort} is hosted.

. Change to the `service-telemetry` project:
+
[source,bash]
----
$ oc project service-telemetry
----

. Retrieve the {MessageBus} password:
+
[source,bash,options="nowrap",subs="verbatim"]
----
$ oc get secret default-interconnect-users -o json | jq -r .data.guest | base64 -d
----
