// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_creating-a-servicetelemetry-object-in-openshift.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.


[id="creating-a-servicetelemetry-object-in-openshift"]
== Creating a ServiceTelemetry object in {OpenShiftShort}

Create a `ServiceTelemetry` object in {OpenShiftShort} to result in the creation of supporting components for a {Project} deployment. For more information, see xref:overview-of-the-servicetelemetry-object[].

.Procedure

. To store events in ElasticSearch, set `eventsEnabled` to true during deployment:
+
[source,bash]
----
oc apply -f - <<EOF
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  name: stf-default
  namespace: service-telemetry
spec:
  eventsEnabled: true
  metricsEnabled: true
EOF
----

. To view the {ProjectShort} deployment logs in the Service Telemetry Operator, use the `oc logs` command:
+
[source,bash]
----
oc logs $(oc get pod --selector='name=service-telemetry-operator' -oname) -c ansible
----
+
[options="nowrap", subs="+quotes"]
----
PLAY RECAP *********************************************************************
localhost                  : ok=68   changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
----



. View the pods and the status of each pod to determine that all workloads are operating nominally:
+
NOTE: If you set `eventsEnabled: true`, the notification Smart Gateways will `Error` and `CrashLoopBackOff` for a period of time before ElasticSearch starts.
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc get pods

NAME                                                              READY   STATUS             RESTARTS   AGE
alertmanager-stf-default-0                                        2/2     Running            0          26m
elastic-operator-645dc8b8ff-jwnzt                                 1/1     Running            0          88m
elasticsearch-es-default-0                                        1/1     Running            0          26m
interconnect-operator-6fd49d9fb9-4bl92                            1/1     Running            0          46m
prometheus-operator-bf7d97fb9-kwnlx                               1/1     Running            0          46m
prometheus-stf-default-0                                          3/3     Running            0          26m
service-telemetry-operator-54f4c99d9b-k7ll6                       2/2     Running            0          46m
smart-gateway-operator-7ff58bcf94-66rvx                           2/2     Running            0          46m
stf-default-ceilometer-notification-smartgateway-7c45b755bzhhw2   1/1     Running            2          26m
stf-default-ceilometer-telemetry-smartgateway-6c99864b45-fwqfc    1/1     Running            0          26m
stf-default-collectd-notification-smartgateway-787974df89-6xpr4   1/1     Running            2          26m
stf-default-collectd-telemetry-smartgateway-68f5cd5ffc-9758h      2/2     Running            0          26m
stf-default-interconnect-7458fd4d69-nqbfs                         1/1     Running            0          26m
----
