// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_setting-up-the-dashboard-to-host-grafana.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="setting-up-grafana-to-host-the-dashboard_{context}"]
= Setting up Grafana to host the dashboard

Grafana is not included in the default {Project} ({ProjectShort}) deployment so you must deploy the Grafana Operator from OperatorHub.io.

[discrete]
.Procedure

. Clone the dashboard repository.
+
----
git clone https://github.com/infrawatch/dashboards
cd dashboards
----

. Change to the `service-telemetry` namespace and deploy the Grafana operator:
+
----
oc project service-telemetry
oc create -f deploy/subscription.yaml
----

. To verify that the operator launched successfully, run the `oc get csv` command. If the value of the PHASE column is Succeeded, the operator launched successfully:
+
[options="nowrap", subs="+quotes"]
----
$ oc get csv

NAME                                DISPLAY                                         VERSION   REPLACES                            PHASE
grafana-operator.v3.2.0             Grafana Operator                                3.2.0                                         Succeeded
...
----

. Launch a Grafana instance:
+
----
$ oc create -f deploy/grafana.yaml
----

. Verify that the Grafana instance deployed:
+
----
$ oc get pod -l app=grafana

NAME                                  READY   STATUS    RESTARTS   AGE
grafana-deployment-7fc7848b56-sbkhv   1/1     Running   0          1m
----

. Create the datasource and dashboard resources:
+
----
oc create -f deploy/datasource.yaml \
    -f deploy/rhos-dashboard.yaml
----

. Verify that the resources installed correctly:
+
----
$ oc get grafanadashboards

NAME             AGE
rhos-dashboard   7d21h

$ oc get grafanadatasources
NAME                                  AGE
service-telemetry-grafanadatasource   1m
----

. Navigate to https://<grafana-route-address> in a web browser. Use the `oc get routes` command to retrieve the Grafana route address:
+
----
oc get routes
----

. To view the dashboard, click *Dashboards* and *Manage*.

[discrete]
.Additional resources

* For more information about enabling the OperatorHub.io catalog source, see xref:enabling-the-operatorhubio-community-catalog-source[].



[id="viewing-and-editing-queries"]
== Viewing and editing queries

[discrete]
.Procedure

. To view and edit queries, log in as the `admin` user.

. To retrieve the default username and password, describe the Grafana object using `oc describe`:
+
----
oc describe grafana service-telemetry-grafana
----
