// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_deploying-smart-gateways.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="deploying-smart-gateways_{context}"]
= Deploying Smart Gateways

You must deploy a Smart Gateway for each of the data collection types for each cloud; one for collectd metrics, one for collectd events, one for Ceilometer metrics, and one for Ceilometer events. Configure each of the Smart Gateways to listen on the AMQP address that you define for the corresponding cloud. Smart Gateways are defined via the `clouds` parameter in the `ServiceTelemetry` manifest.

When you deploy {ProjectShort} for the first time, Smart Gateway manifests are created that define the initial Smart Gateways for a single cloud. When deploying Smart Gateways for multiple cloud support, you deploy multiple Smart Gateways for each of the data collection types that handle the metrics and the events data for each cloud. The initial Smart Gateways are defined under `cloud1` with the following subscription addresses:

|===
| **collector** | **type** | **default subscription address**
| collectd | metrics | collectd/telemetry
| collectd | events | collectd/notify
| Ceilometer | metrics | anycast/ceilometer/metering.sample
| Ceilometer | events | anycast/ceilometer/event.sample
|===

.Prerequisites

You have determined your naming scheme and have created your list of clouds objects. For more information about determining your naming scheme, see xref:planning-amqp-address-prefixes_advanced-features[]. For more information about creating the content for the `clouds` parameter, see xref:clouds_installing-the-core-components-of-stf[].

.Procedure

. Log in to {OpenShift}.
. Change to the `service-telemetry` namespace:
+
----
oc project service-telemetry
----

. Edit the `default` ServiceTelemetry object and add a `clouds` parameter with your configuration:
+
----
oc edit stf default
----
+
----
apiVersion: infra.watch/v1beta1
kind: ServiceTelemetry
metadata:
  ...
spec:
  ...
  clouds:
  - name: cloud1
    events:
      collectors:
      - collectorType: collectd
        subscriptionAddress: collectd/cloud1-notify
      - collectorType: ceilometer
        subscriptionAddress: anycast/ceilometer/cloud1-event.sample
    metrics:
      collectors:
      - collectorType: collectd
        subscriptionAddress: collectd/cloud1-telemetry
      - collectorType: ceilometer
        subscriptionAddress: anycast/ceilometer/cloud1-metering.sample
  - name: cloud2
    events:
      ...
----

. Save the ServiceTelemetry object.

. Verify that each Smart Gateway is running. This can take several minutes depending on the number of Smart Gateways:
+
----
oc get po -l app=smart-gateway
----
+
----
NAME                                                      READY   STATUS    RESTARTS   AGE
default-cloud1-ceil-event-smartgateway-6cfb65478c-g5q82   1/1     Running   0          13h
default-cloud1-ceil-meter-smartgateway-58f885c76d-xmxwn   1/1     Running   0          13h
default-cloud1-coll-event-smartgateway-58fbbd4485-rl9bd   1/1     Running   0          13h
default-cloud1-coll-meter-smartgateway-7c6fc495c4-jn728   2/2     Running   0          13h
----
