= Sending metrics to Gnocchi and to {ProjectShort}

[role="_abstract"]

To send metrics to {Project} ({ProjectShort}} and Gnocchi simultaneously, you must include an environment file in your deployment to enable an additional publisher.

.Prerequisites

* You have created a file that contains the connection configuration of the {MessageBus} for the overcloud to {ProjectShort}. For more information, see xref:configuring-the-stf-connection-for-the-overcloud[].

.Procedure

. Create an environment file named `gnocchi-connectors.yaml` in the
`/home/stack` directory.
+
[source,yaml,options="nowrap",subs="none"]
----
resource_registry:
    OS::TripleO::Services::GnocchiApi: /usr/share/openstack-tripleo-heat-templates/deployment/gnocchi/gnocchi-api-container-puppet.yaml
    OS::TripleO::Services::GnocchiMetricd: /usr/share/openstack-tripleo-heat-templates/deployment/gnocchi/gnocchi-metricd-container-puppet.yaml
    OS::TripleO::Services::GnocchiStatsd: /usr/share/openstack-tripleo-heat-templates/deployment/gnocchi/gnocchi-statsd-container-puppet.yaml
    OS::TripleO::Services::AodhApi: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-api-container-puppet.yaml
    OS::TripleO::Services::AodhEvaluator: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-evaluator-container-puppet.yaml
    OS::TripleO::Services::AodhNotifier: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-notifier-container-puppet.yaml
    OS::TripleO::Services::AodhListener: /usr/share/openstack-tripleo-heat-templates/deployment/aodh/aodh-listener-container-puppet.yaml
    OS::TripleO::Services::PankoApi: /usr/share/openstack-tripleo-heat-templates/deployment/deprecated/panko/panko-api-container-puppet.yaml

parameter_defaults:
    CeilometerEnableGnocchi: true
    CeilometerEnablePanko: false
    GnocchiArchivePolicy: 'high'
    GnocchiBackend: 'rbd'
    GnocchiRbdPoolName: 'metrics'

    EventPipelinePublishers: ['gnocchi://?filter_project=service&archive_policy=high']
    PipelinePublishers: ['gnocchi://?filter_project=service&archive_policy=high']
----

. Add the environment file `gnocchi-connectors.yaml` to the deployment command. Replace <other-argruments> with files that are applicable to your environment:
+
[source,bash,options="nowrap",subs="+quotes"]
----
openstack overcloud deploy <other arguments>
--templates /usr/share/openstack-tripleo-heat-templates \
  --environment-file <...other-environment-files...> \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/ceilometer-write-qdr.yaml \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/collectd-write-qdr.yaml \
  --environment-file /usr/share/openstack-tripleo-heat-templates/environments/metrics/qdr-edge-only.yaml \
  --environment-file /home/stack/enable-stf.yaml \
  --environment-file /home/stack/stf-connectors.yaml \
  --environment-file /home/stack/gnocchi-connectors.yaml
----

. To verify that the configuration was successful, verify the content of the file `/var/lib/config-data/puppet-generated/ceilometer/etc/ceilometer/pipeline.yaml` on a Controller node. Ensure that the `publishers` section of the file contains information for both notifier and Gnocchi.
+
[source,yaml,options="nowrap",subs="+quotes"]
----
sources:
    - name: meter_source
      meters:
          - "*"
      sinks:
          - meter_sink
sinks:
    - name: meter_sink
      publishers:
          - gnocchi://?filter_project=service&archive_policy=high
          - notifier://172.17.1.35:5666/?driver=amqp&topic=metering
----