// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/proc_removing-stf-from-the-openshift-environment.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: proc_doing-procedure-a.adoc
// * ID: [id='proc_doing-procedure-a_{context}']
// * Title: = Doing procedure A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// Start the title with a verb, such as Creating or Create. See also
// _Wording of headings_ in _The IBM Style Guide_.
[id="removing-stf-from-the-openshift-environment_{context}"]
= Removing {ProjectShort} from the {OpenShiftShort} environment

Remove {ProjectShort} from an {OpenShiftShort} environment if you no longer require the {ProjectShort} functionality:

. Delete the namespace. For more information, see xref:deleting-the-namespace[].
. Delete the OperatorSource. For more information, see xref:removing-the-operatorsource[].

[id="deleting-the-namespace"]
== Deleting the namespace

To remove the operational resources for {ProjectShort} from {OpenShiftShort}, delete the namespace.

[discrete]
=== Procedure

. Run the `oc delete` command:
+
----
oc delete project service-telemetry
----

. Verify that the resources have been deleted from the namespace:
+
----
$ oc get all
No resources found.
----

[id="removing-the-operatorsource"]
== Removing the OperatorSource

If you do not expect to install {Project} again, delete the OperatorSource. When you remove the OperatorSource, PackageManifests related to {ProjectShort} are removed from the Operator Lifecycle Manager catalog.

[discrete]
=== Procedure

. Delete the OperatorSource:
+
ifeval::["{build}" == "upstream"]
----
$ oc delete --namespace=openshift-marketplace operatorsource infrawatch-operators
operatorsource.operators.coreos.com "infrawatch-operators" deleted
----
endif::[]
ifeval::["{build}" == "downstream"]
----
$ oc delete --namespace=openshift-marketplace operatorsource redhat-operators-stf
operatorsource.operators.coreos.com "redhat-operators-stf" deleted
----
endif::[]

. Verify that the {ProjectShort} PackageManifests are removed from the platform. If successful, the following command returns no result:
+
ifeval::["{build}" == "upstream"]
----
$ oc get packagemanifests | grep InfraWatch
----
endif::[]
ifeval::["{build}" == "downstream"]
----
$ oc get packagemanifests | grep "Red Hat STF"
----
endif::[]
+
. If you enabled the OperatorHub.io Community Catalog Source during the installation process and you no longer need this catalog source, delete it:
+
----
$ oc delete --namespace=openshift-marketplace catalogsource operatorhubio-operators
catalogsource.operators.coreos.com "operatorhubio-operators" deleted
----

[discrete]
=== Additional resources
For more information about the OperatorHub.io Community Catalog Source, see xref:deploying-stf-to-the-openshift-environment_installing-the-core-components-of-stf[].
